// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void example (
hls::stream<struct stream256Word >& prt_nw2sbu,
hls::stream<struct stream256Word >& prt_cx2sbu,
hls::stream<struct stream256Word >& mlx2sbu,
hls::stream<struct stream256Word >& sbu2prt_cx,
hls::stream<struct stream256Word >& sbu2prt_nw,
hls::stream<struct stream256Word >& sbu2mlx);
