-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity example_axi_stream_pass_alt is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    In_r_TDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    In_r_TVALID : IN STD_LOGIC;
    In_r_TREADY : OUT STD_LOGIC;
    In_r_TKEEP : IN STD_LOGIC_VECTOR (31 downto 0);
    In_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    In_r_TID : IN STD_LOGIC_VECTOR (2 downto 0);
    In_r_TUSER : IN STD_LOGIC_VECTOR (11 downto 0);
    Out_r_TDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    Out_r_TVALID : OUT STD_LOGIC;
    Out_r_TREADY : IN STD_LOGIC;
    Out_r_TKEEP : OUT STD_LOGIC_VECTOR (31 downto 0);
    Out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    Out_r_TID : OUT STD_LOGIC_VECTOR (2 downto 0);
    Out_r_TUSER : OUT STD_LOGIC_VECTOR (11 downto 0);
    In_r_TDATA_blk_n : OUT STD_LOGIC;
    Out_r_TDATA_blk_n : OUT STD_LOGIC );
end;


architecture behav of example_axi_stream_pass_alt is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_18 : BOOLEAN;
    signal tmp_nbreadreq_fu_36_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_55 : BOOLEAN;
    signal ap_sig_ioackin_Out_r_TREADY : STD_LOGIC;
    signal ap_reg_ioackin_Out_r_TREADY : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_ioackin_Out_r_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_Out_r_TREADY <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and not((ap_sig_55 or (not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and (ap_const_logic_0 = ap_sig_ioackin_Out_r_TREADY))))))) then 
                    ap_reg_ioackin_Out_r_TREADY <= ap_const_logic_0;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and not(ap_sig_55) and (ap_const_logic_1 = Out_r_TREADY)))) then 
                    ap_reg_ioackin_Out_r_TREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, tmp_nbreadreq_fu_36_p7, ap_sig_55, ap_sig_ioackin_Out_r_TREADY)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    In_r_TDATA_blk_n_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, In_r_TVALID, tmp_nbreadreq_fu_36_p7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)))) then 
            In_r_TDATA_blk_n <= In_r_TVALID;
        else 
            In_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    In_r_TREADY_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_nbreadreq_fu_36_p7, ap_sig_55, ap_sig_ioackin_Out_r_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and not((ap_sig_55 or (not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and (ap_const_logic_0 = ap_sig_ioackin_Out_r_TREADY))))))) then 
            In_r_TREADY <= ap_const_logic_1;
        else 
            In_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    Out_r_TDATA <= In_r_TDATA;

    Out_r_TDATA_blk_n_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, Out_r_TREADY, tmp_nbreadreq_fu_36_p7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)))) then 
            Out_r_TDATA_blk_n <= Out_r_TREADY;
        else 
            Out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Out_r_TID <= In_r_TID;
    Out_r_TKEEP <= In_r_TKEEP;
    Out_r_TLAST <= In_r_TLAST;
    Out_r_TUSER <= In_r_TUSER;

    Out_r_TVALID_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_nbreadreq_fu_36_p7, ap_sig_55, ap_reg_ioackin_Out_r_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and not(ap_sig_55) and (ap_const_logic_0 = ap_reg_ioackin_Out_r_TREADY)))) then 
            Out_r_TVALID <= ap_const_logic_1;
        else 
            Out_r_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, tmp_nbreadreq_fu_36_p7, ap_sig_55, ap_sig_ioackin_Out_r_TREADY)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_sig_55 or (not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and (ap_const_logic_0 = ap_sig_ioackin_Out_r_TREADY))))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_nbreadreq_fu_36_p7, ap_sig_55, ap_sig_ioackin_Out_r_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_sig_55 or (not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and (ap_const_logic_0 = ap_sig_ioackin_Out_r_TREADY)))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_18_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_18 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_55_assign_proc : process(ap_start, In_r_TVALID, tmp_nbreadreq_fu_36_p7)
    begin
                ap_sig_55 <= ((not((tmp_nbreadreq_fu_36_p7 = ap_const_lv1_0)) and (In_r_TVALID = ap_const_logic_0)) or (ap_start = ap_const_logic_0));
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_18)
    begin
        if (ap_sig_18) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_ioackin_Out_r_TREADY_assign_proc : process(Out_r_TREADY, ap_reg_ioackin_Out_r_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_Out_r_TREADY)) then 
            ap_sig_ioackin_Out_r_TREADY <= Out_r_TREADY;
        else 
            ap_sig_ioackin_Out_r_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    tmp_nbreadreq_fu_36_p7 <= (0=>(In_r_TVALID), others=>'-');
end behav;
