// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "example.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<256> example::ap_const_lv256_lc_1 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> example::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> example::ap_const_lv1_0 = "0";
const sc_lv<3> example::ap_const_lv3_0 = "000";
const sc_lv<12> example::ap_const_lv12_0 = "000000000000";
const sc_logic example::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic example::ap_const_logic_0 = sc_dt::Log_0;
const bool example::ap_true = true;

example::example(sc_module_name name) : sc_module(name), mVcdFile(0) {
    example_Block_codeRepl951_proc_U0 = new example_Block_codeRepl951_proc("example_Block_codeRepl951_proc_U0");
    example_Block_codeRepl951_proc_U0->ap_clk(ap_clk);
    example_Block_codeRepl951_proc_U0->ap_rst(ap_rst_n_inv);
    example_Block_codeRepl951_proc_U0->ap_start(example_Block_codeRepl951_proc_U0_ap_start);
    example_Block_codeRepl951_proc_U0->ap_done(example_Block_codeRepl951_proc_U0_ap_done);
    example_Block_codeRepl951_proc_U0->ap_continue(example_Block_codeRepl951_proc_U0_ap_continue);
    example_Block_codeRepl951_proc_U0->ap_idle(example_Block_codeRepl951_proc_U0_ap_idle);
    example_Block_codeRepl951_proc_U0->ap_ready(example_Block_codeRepl951_proc_U0_ap_ready);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TDATA(prt_nw2sbu_TDATA);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TVALID(prt_nw2sbu_TVALID);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TREADY(example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TKEEP(prt_nw2sbu_TKEEP);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TLAST(prt_nw2sbu_TLAST);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TID(prt_nw2sbu_TID);
    example_Block_codeRepl951_proc_U0->prt_nw2sbu_TUSER(prt_nw2sbu_TUSER);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TDATA(prt_cx2sbu_TDATA);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TVALID(prt_cx2sbu_TVALID);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TREADY(example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TKEEP(prt_cx2sbu_TKEEP);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TLAST(prt_cx2sbu_TLAST);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TID(prt_cx2sbu_TID);
    example_Block_codeRepl951_proc_U0->prt_cx2sbu_TUSER(prt_cx2sbu_TUSER);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TDATA(mlx2sbu_TDATA);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TVALID(mlx2sbu_TVALID);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TREADY(example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TKEEP(mlx2sbu_TKEEP);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TLAST(mlx2sbu_TLAST);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TID(mlx2sbu_TID);
    example_Block_codeRepl951_proc_U0->mlx2sbu_TUSER(mlx2sbu_TUSER);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TDATA(example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TVALID(example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TREADY(sbu2mlx_TREADY);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TKEEP(example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TLAST(example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TID(example_Block_codeRepl951_proc_U0_sbu2mlx_TID);
    example_Block_codeRepl951_proc_U0->sbu2mlx_TUSER(example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TDATA(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TVALID(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TREADY(sbu2prt_nw_TREADY);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TKEEP(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TLAST(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TID(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID);
    example_Block_codeRepl951_proc_U0->sbu2prt_nw_TUSER(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TDATA(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TVALID(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TREADY(sbu2prt_cx_TREADY);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TKEEP(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TLAST(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TID(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID);
    example_Block_codeRepl951_proc_U0->sbu2prt_cx_TUSER(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( example_Block_codeRepl951_proc_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( example_Block_codeRepl951_proc_U0_ap_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( example_Block_codeRepl951_proc_U0_ap_done );

    SC_METHOD(thread_ap_sig_hs_ready);
    sensitive << ( example_Block_codeRepl951_proc_U0_ap_ready );

    SC_METHOD(thread_example_Block_codeRepl951_proc_U0_ap_continue);

    SC_METHOD(thread_example_Block_codeRepl951_proc_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_mlx2sbu_TREADY);
    sensitive << ( example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY );

    SC_METHOD(thread_prt_cx2sbu_TREADY);
    sensitive << ( example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY );

    SC_METHOD(thread_prt_nw2sbu_TREADY);
    sensitive << ( example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY );

    SC_METHOD(thread_sbu2mlx_TDATA);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA );

    SC_METHOD(thread_sbu2mlx_TID);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2mlx_TID );

    SC_METHOD(thread_sbu2mlx_TKEEP);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP );

    SC_METHOD(thread_sbu2mlx_TLAST);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST );

    SC_METHOD(thread_sbu2mlx_TUSER);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER );

    SC_METHOD(thread_sbu2mlx_TVALID);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID );

    SC_METHOD(thread_sbu2prt_cx_TDATA);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA );

    SC_METHOD(thread_sbu2prt_cx_TID);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID );

    SC_METHOD(thread_sbu2prt_cx_TKEEP);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP );

    SC_METHOD(thread_sbu2prt_cx_TLAST);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST );

    SC_METHOD(thread_sbu2prt_cx_TUSER);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER );

    SC_METHOD(thread_sbu2prt_cx_TVALID);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID );

    SC_METHOD(thread_sbu2prt_nw_TDATA);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA );

    SC_METHOD(thread_sbu2prt_nw_TID);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID );

    SC_METHOD(thread_sbu2prt_nw_TKEEP);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP );

    SC_METHOD(thread_sbu2prt_nw_TLAST);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST );

    SC_METHOD(thread_sbu2prt_nw_TUSER);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER );

    SC_METHOD(thread_sbu2prt_nw_TVALID);
    sensitive << ( example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "example_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, prt_nw2sbu_TDATA, "(port)prt_nw2sbu_TDATA");
    sc_trace(mVcdFile, prt_nw2sbu_TKEEP, "(port)prt_nw2sbu_TKEEP");
    sc_trace(mVcdFile, prt_nw2sbu_TLAST, "(port)prt_nw2sbu_TLAST");
    sc_trace(mVcdFile, prt_nw2sbu_TID, "(port)prt_nw2sbu_TID");
    sc_trace(mVcdFile, prt_nw2sbu_TUSER, "(port)prt_nw2sbu_TUSER");
    sc_trace(mVcdFile, prt_cx2sbu_TDATA, "(port)prt_cx2sbu_TDATA");
    sc_trace(mVcdFile, prt_cx2sbu_TKEEP, "(port)prt_cx2sbu_TKEEP");
    sc_trace(mVcdFile, prt_cx2sbu_TLAST, "(port)prt_cx2sbu_TLAST");
    sc_trace(mVcdFile, prt_cx2sbu_TID, "(port)prt_cx2sbu_TID");
    sc_trace(mVcdFile, prt_cx2sbu_TUSER, "(port)prt_cx2sbu_TUSER");
    sc_trace(mVcdFile, mlx2sbu_TDATA, "(port)mlx2sbu_TDATA");
    sc_trace(mVcdFile, mlx2sbu_TKEEP, "(port)mlx2sbu_TKEEP");
    sc_trace(mVcdFile, mlx2sbu_TLAST, "(port)mlx2sbu_TLAST");
    sc_trace(mVcdFile, mlx2sbu_TID, "(port)mlx2sbu_TID");
    sc_trace(mVcdFile, mlx2sbu_TUSER, "(port)mlx2sbu_TUSER");
    sc_trace(mVcdFile, sbu2prt_cx_TDATA, "(port)sbu2prt_cx_TDATA");
    sc_trace(mVcdFile, sbu2prt_cx_TKEEP, "(port)sbu2prt_cx_TKEEP");
    sc_trace(mVcdFile, sbu2prt_cx_TLAST, "(port)sbu2prt_cx_TLAST");
    sc_trace(mVcdFile, sbu2prt_cx_TID, "(port)sbu2prt_cx_TID");
    sc_trace(mVcdFile, sbu2prt_cx_TUSER, "(port)sbu2prt_cx_TUSER");
    sc_trace(mVcdFile, sbu2prt_nw_TDATA, "(port)sbu2prt_nw_TDATA");
    sc_trace(mVcdFile, sbu2prt_nw_TKEEP, "(port)sbu2prt_nw_TKEEP");
    sc_trace(mVcdFile, sbu2prt_nw_TLAST, "(port)sbu2prt_nw_TLAST");
    sc_trace(mVcdFile, sbu2prt_nw_TID, "(port)sbu2prt_nw_TID");
    sc_trace(mVcdFile, sbu2prt_nw_TUSER, "(port)sbu2prt_nw_TUSER");
    sc_trace(mVcdFile, sbu2mlx_TDATA, "(port)sbu2mlx_TDATA");
    sc_trace(mVcdFile, sbu2mlx_TKEEP, "(port)sbu2mlx_TKEEP");
    sc_trace(mVcdFile, sbu2mlx_TLAST, "(port)sbu2mlx_TLAST");
    sc_trace(mVcdFile, sbu2mlx_TID, "(port)sbu2mlx_TID");
    sc_trace(mVcdFile, sbu2mlx_TUSER, "(port)sbu2mlx_TUSER");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, prt_nw2sbu_TVALID, "(port)prt_nw2sbu_TVALID");
    sc_trace(mVcdFile, prt_nw2sbu_TREADY, "(port)prt_nw2sbu_TREADY");
    sc_trace(mVcdFile, prt_cx2sbu_TVALID, "(port)prt_cx2sbu_TVALID");
    sc_trace(mVcdFile, prt_cx2sbu_TREADY, "(port)prt_cx2sbu_TREADY");
    sc_trace(mVcdFile, mlx2sbu_TVALID, "(port)mlx2sbu_TVALID");
    sc_trace(mVcdFile, mlx2sbu_TREADY, "(port)mlx2sbu_TREADY");
    sc_trace(mVcdFile, sbu2mlx_TVALID, "(port)sbu2mlx_TVALID");
    sc_trace(mVcdFile, sbu2mlx_TREADY, "(port)sbu2mlx_TREADY");
    sc_trace(mVcdFile, sbu2prt_nw_TVALID, "(port)sbu2prt_nw_TVALID");
    sc_trace(mVcdFile, sbu2prt_nw_TREADY, "(port)sbu2prt_nw_TREADY");
    sc_trace(mVcdFile, sbu2prt_cx_TVALID, "(port)sbu2prt_cx_TVALID");
    sc_trace(mVcdFile, sbu2prt_cx_TREADY, "(port)sbu2prt_cx_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_ap_start, "example_Block_codeRepl951_proc_U0_ap_start");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_ap_done, "example_Block_codeRepl951_proc_U0_ap_done");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_ap_continue, "example_Block_codeRepl951_proc_U0_ap_continue");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_ap_idle, "example_Block_codeRepl951_proc_U0_ap_idle");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_ap_ready, "example_Block_codeRepl951_proc_U0_ap_ready");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY, "example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY, "example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY, "example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA, "example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID, "example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP, "example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST, "example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2mlx_TID, "example_Block_codeRepl951_proc_U0_sbu2mlx_TID");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER, "example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA, "example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID, "example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP, "example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST, "example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID, "example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER, "example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA, "example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID, "example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP, "example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST, "example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID, "example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID");
    sc_trace(mVcdFile, example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER, "example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_sig_hs_ready, "ap_sig_hs_ready");
#endif

    }
    mHdltvinHandle.open("example.hdltvin.dat");
    mHdltvoutHandle.open("example.hdltvout.dat");
}

example::~example() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete example_Block_codeRepl951_proc_U0;
}

void example::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void example::thread_ap_idle() {
    if (esl_seteq<1,1,1>(example_Block_codeRepl951_proc_U0_ap_idle.read(), ap_const_logic_1)) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void example::thread_ap_ready() {
    ap_ready = example_Block_codeRepl951_proc_U0_ap_ready.read();
}

void example::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void example::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void example::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(example_Block_codeRepl951_proc_U0_ap_done.read(), ap_const_logic_1)) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void example::thread_ap_sig_hs_ready() {
    ap_sig_hs_ready = example_Block_codeRepl951_proc_U0_ap_ready.read();
}

void example::thread_example_Block_codeRepl951_proc_U0_ap_continue() {
    example_Block_codeRepl951_proc_U0_ap_continue = ap_const_logic_1;
}

void example::thread_example_Block_codeRepl951_proc_U0_ap_start() {
    example_Block_codeRepl951_proc_U0_ap_start = ap_start.read();
}

void example::thread_mlx2sbu_TREADY() {
    mlx2sbu_TREADY = example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY.read();
}

void example::thread_prt_cx2sbu_TREADY() {
    prt_cx2sbu_TREADY = example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY.read();
}

void example::thread_prt_nw2sbu_TREADY() {
    prt_nw2sbu_TREADY = example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY.read();
}

void example::thread_sbu2mlx_TDATA() {
    sbu2mlx_TDATA = example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA.read();
}

void example::thread_sbu2mlx_TID() {
    sbu2mlx_TID = example_Block_codeRepl951_proc_U0_sbu2mlx_TID.read();
}

void example::thread_sbu2mlx_TKEEP() {
    sbu2mlx_TKEEP = example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP.read();
}

void example::thread_sbu2mlx_TLAST() {
    sbu2mlx_TLAST = example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST.read();
}

void example::thread_sbu2mlx_TUSER() {
    sbu2mlx_TUSER = example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER.read();
}

void example::thread_sbu2mlx_TVALID() {
    sbu2mlx_TVALID = example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID.read();
}

void example::thread_sbu2prt_cx_TDATA() {
    sbu2prt_cx_TDATA = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA.read();
}

void example::thread_sbu2prt_cx_TID() {
    sbu2prt_cx_TID = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID.read();
}

void example::thread_sbu2prt_cx_TKEEP() {
    sbu2prt_cx_TKEEP = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP.read();
}

void example::thread_sbu2prt_cx_TLAST() {
    sbu2prt_cx_TLAST = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST.read();
}

void example::thread_sbu2prt_cx_TUSER() {
    sbu2prt_cx_TUSER = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER.read();
}

void example::thread_sbu2prt_cx_TVALID() {
    sbu2prt_cx_TVALID = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID.read();
}

void example::thread_sbu2prt_nw_TDATA() {
    sbu2prt_nw_TDATA = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA.read();
}

void example::thread_sbu2prt_nw_TID() {
    sbu2prt_nw_TID = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID.read();
}

void example::thread_sbu2prt_nw_TKEEP() {
    sbu2prt_nw_TKEEP = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP.read();
}

void example::thread_sbu2prt_nw_TLAST() {
    sbu2prt_nw_TLAST = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST.read();
}

void example::thread_sbu2prt_nw_TUSER() {
    sbu2prt_nw_TUSER = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER.read();
}

void example::thread_sbu2prt_nw_TVALID() {
    sbu2prt_nw_TVALID = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID.read();
}

void example::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"prt_nw2sbu_TDATA\" :  \"" << prt_nw2sbu_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_nw2sbu_TKEEP\" :  \"" << prt_nw2sbu_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_nw2sbu_TLAST\" :  \"" << prt_nw2sbu_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_nw2sbu_TID\" :  \"" << prt_nw2sbu_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_nw2sbu_TUSER\" :  \"" << prt_nw2sbu_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_cx2sbu_TDATA\" :  \"" << prt_cx2sbu_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_cx2sbu_TKEEP\" :  \"" << prt_cx2sbu_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_cx2sbu_TLAST\" :  \"" << prt_cx2sbu_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_cx2sbu_TID\" :  \"" << prt_cx2sbu_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_cx2sbu_TUSER\" :  \"" << prt_cx2sbu_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlx2sbu_TDATA\" :  \"" << mlx2sbu_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlx2sbu_TKEEP\" :  \"" << mlx2sbu_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlx2sbu_TLAST\" :  \"" << mlx2sbu_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlx2sbu_TID\" :  \"" << mlx2sbu_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlx2sbu_TUSER\" :  \"" << mlx2sbu_TUSER.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"sbu2prt_cx_TDATA\" :  \"" << sbu2prt_cx_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_cx_TKEEP\" :  \"" << sbu2prt_cx_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_cx_TLAST\" :  \"" << sbu2prt_cx_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_cx_TID\" :  \"" << sbu2prt_cx_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_cx_TUSER\" :  \"" << sbu2prt_cx_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_nw_TDATA\" :  \"" << sbu2prt_nw_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_nw_TKEEP\" :  \"" << sbu2prt_nw_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_nw_TLAST\" :  \"" << sbu2prt_nw_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_nw_TID\" :  \"" << sbu2prt_nw_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_nw_TUSER\" :  \"" << sbu2prt_nw_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2mlx_TDATA\" :  \"" << sbu2mlx_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2mlx_TKEEP\" :  \"" << sbu2mlx_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2mlx_TLAST\" :  \"" << sbu2mlx_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2mlx_TID\" :  \"" << sbu2mlx_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2mlx_TUSER\" :  \"" << sbu2mlx_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_nw2sbu_TVALID\" :  \"" << prt_nw2sbu_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"prt_nw2sbu_TREADY\" :  \"" << prt_nw2sbu_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prt_cx2sbu_TVALID\" :  \"" << prt_cx2sbu_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"prt_cx2sbu_TREADY\" :  \"" << prt_cx2sbu_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlx2sbu_TVALID\" :  \"" << mlx2sbu_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mlx2sbu_TREADY\" :  \"" << mlx2sbu_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2mlx_TVALID\" :  \"" << sbu2mlx_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sbu2mlx_TREADY\" :  \"" << sbu2mlx_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_nw_TVALID\" :  \"" << sbu2prt_nw_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sbu2prt_nw_TREADY\" :  \"" << sbu2prt_nw_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sbu2prt_cx_TVALID\" :  \"" << sbu2prt_cx_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sbu2prt_cx_TREADY\" :  \"" << sbu2prt_cx_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

