:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2016.2
:: Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado_HLS/2016.2/../../Vivado/2016.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcku060-ffva1156-1l-i ../Mellanox_hls_example_1_0.zip
