// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      example
`define AUTOTB_DUT_INST AESL_inst_example
`define AUTOTB_TOP      apatb_example_top
`define AUTOTB_LAT_RESULT_FILE "example.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "example.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_example_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_CLOCK_PERIOD_DIV2 2.30

`define AESL_DEPTH_prt_nw2sbu_V_data_V 1
`define AESL_DEPTH_prt_nw2sbu_V_keep_V 1
`define AESL_DEPTH_prt_nw2sbu_V_last_V 1
`define AESL_DEPTH_prt_nw2sbu_V_id_V 1
`define AESL_DEPTH_prt_nw2sbu_V_user_V 1
`define AESL_DEPTH_prt_cx2sbu_V_data_V 1
`define AESL_DEPTH_prt_cx2sbu_V_keep_V 1
`define AESL_DEPTH_prt_cx2sbu_V_last_V 1
`define AESL_DEPTH_prt_cx2sbu_V_id_V 1
`define AESL_DEPTH_prt_cx2sbu_V_user_V 1
`define AESL_DEPTH_mlx2sbu_V_data_V 1
`define AESL_DEPTH_mlx2sbu_V_keep_V 1
`define AESL_DEPTH_mlx2sbu_V_last_V 1
`define AESL_DEPTH_mlx2sbu_V_id_V 1
`define AESL_DEPTH_mlx2sbu_V_user_V 1
`define AESL_DEPTH_sbu2prt_cx_V_data_V 1
`define AESL_DEPTH_sbu2prt_cx_V_keep_V 1
`define AESL_DEPTH_sbu2prt_cx_V_last_V 1
`define AESL_DEPTH_sbu2prt_cx_V_id_V 1
`define AESL_DEPTH_sbu2prt_cx_V_user_V 1
`define AESL_DEPTH_sbu2prt_nw_V_data_V 1
`define AESL_DEPTH_sbu2prt_nw_V_keep_V 1
`define AESL_DEPTH_sbu2prt_nw_V_last_V 1
`define AESL_DEPTH_sbu2prt_nw_V_id_V 1
`define AESL_DEPTH_sbu2prt_nw_V_user_V 1
`define AESL_DEPTH_sbu2mlx_V_data_V 1
`define AESL_DEPTH_sbu2mlx_V_keep_V 1
`define AESL_DEPTH_sbu2mlx_V_last_V 1
`define AESL_DEPTH_sbu2mlx_V_id_V 1
`define AESL_DEPTH_sbu2mlx_V_user_V 1
`define AUTOTB_TVIN_prt_nw2sbu_V_data_V  "./c.example.autotvin_prt_nw2sbu_V_data_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_keep_V  "./c.example.autotvin_prt_nw2sbu_V_keep_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_last_V  "./c.example.autotvin_prt_nw2sbu_V_last_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_id_V  "./c.example.autotvin_prt_nw2sbu_V_id_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_user_V  "./c.example.autotvin_prt_nw2sbu_V_user_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_data_V  "./c.example.autotvin_prt_cx2sbu_V_data_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_keep_V  "./c.example.autotvin_prt_cx2sbu_V_keep_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_last_V  "./c.example.autotvin_prt_cx2sbu_V_last_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_id_V  "./c.example.autotvin_prt_cx2sbu_V_id_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_user_V  "./c.example.autotvin_prt_cx2sbu_V_user_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_data_V  "./c.example.autotvin_mlx2sbu_V_data_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_keep_V  "./c.example.autotvin_mlx2sbu_V_keep_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_last_V  "./c.example.autotvin_mlx2sbu_V_last_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_id_V  "./c.example.autotvin_mlx2sbu_V_id_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_user_V  "./c.example.autotvin_mlx2sbu_V_user_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_data_V  "./c.example.autotvin_sbu2prt_cx_V_data_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_keep_V  "./c.example.autotvin_sbu2prt_cx_V_keep_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_last_V  "./c.example.autotvin_sbu2prt_cx_V_last_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_id_V  "./c.example.autotvin_sbu2prt_cx_V_id_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_user_V  "./c.example.autotvin_sbu2prt_cx_V_user_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_data_V  "./c.example.autotvin_sbu2prt_nw_V_data_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_keep_V  "./c.example.autotvin_sbu2prt_nw_V_keep_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_last_V  "./c.example.autotvin_sbu2prt_nw_V_last_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_id_V  "./c.example.autotvin_sbu2prt_nw_V_id_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_user_V  "./c.example.autotvin_sbu2prt_nw_V_user_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_data_V  "./c.example.autotvin_sbu2mlx_V_data_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_keep_V  "./c.example.autotvin_sbu2mlx_V_keep_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_last_V  "./c.example.autotvin_sbu2mlx_V_last_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_id_V  "./c.example.autotvin_sbu2mlx_V_id_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_user_V  "./c.example.autotvin_sbu2mlx_V_user_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_data_V_out_wrapc  "./rtl.example.autotvin_prt_nw2sbu_V_data_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_keep_V_out_wrapc  "./rtl.example.autotvin_prt_nw2sbu_V_keep_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_last_V_out_wrapc  "./rtl.example.autotvin_prt_nw2sbu_V_last_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_id_V_out_wrapc  "./rtl.example.autotvin_prt_nw2sbu_V_id_V.dat"
`define AUTOTB_TVIN_prt_nw2sbu_V_user_V_out_wrapc  "./rtl.example.autotvin_prt_nw2sbu_V_user_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_data_V_out_wrapc  "./rtl.example.autotvin_prt_cx2sbu_V_data_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_keep_V_out_wrapc  "./rtl.example.autotvin_prt_cx2sbu_V_keep_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_last_V_out_wrapc  "./rtl.example.autotvin_prt_cx2sbu_V_last_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_id_V_out_wrapc  "./rtl.example.autotvin_prt_cx2sbu_V_id_V.dat"
`define AUTOTB_TVIN_prt_cx2sbu_V_user_V_out_wrapc  "./rtl.example.autotvin_prt_cx2sbu_V_user_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_data_V_out_wrapc  "./rtl.example.autotvin_mlx2sbu_V_data_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_keep_V_out_wrapc  "./rtl.example.autotvin_mlx2sbu_V_keep_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_last_V_out_wrapc  "./rtl.example.autotvin_mlx2sbu_V_last_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_id_V_out_wrapc  "./rtl.example.autotvin_mlx2sbu_V_id_V.dat"
`define AUTOTB_TVIN_mlx2sbu_V_user_V_out_wrapc  "./rtl.example.autotvin_mlx2sbu_V_user_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_data_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_cx_V_data_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_keep_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_cx_V_keep_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_last_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_cx_V_last_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_id_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_cx_V_id_V.dat"
`define AUTOTB_TVIN_sbu2prt_cx_V_user_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_cx_V_user_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_data_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_nw_V_data_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_keep_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_nw_V_keep_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_last_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_nw_V_last_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_id_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_nw_V_id_V.dat"
`define AUTOTB_TVIN_sbu2prt_nw_V_user_V_out_wrapc  "./rtl.example.autotvin_sbu2prt_nw_V_user_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_data_V_out_wrapc  "./rtl.example.autotvin_sbu2mlx_V_data_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_keep_V_out_wrapc  "./rtl.example.autotvin_sbu2mlx_V_keep_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_last_V_out_wrapc  "./rtl.example.autotvin_sbu2mlx_V_last_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_id_V_out_wrapc  "./rtl.example.autotvin_sbu2mlx_V_id_V.dat"
`define AUTOTB_TVIN_sbu2mlx_V_user_V_out_wrapc  "./rtl.example.autotvin_sbu2mlx_V_user_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_data_V  "./c.example.autotvout_sbu2prt_cx_V_data_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_keep_V  "./c.example.autotvout_sbu2prt_cx_V_keep_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_last_V  "./c.example.autotvout_sbu2prt_cx_V_last_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_id_V  "./c.example.autotvout_sbu2prt_cx_V_id_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_user_V  "./c.example.autotvout_sbu2prt_cx_V_user_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_data_V  "./c.example.autotvout_sbu2prt_nw_V_data_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_keep_V  "./c.example.autotvout_sbu2prt_nw_V_keep_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_last_V  "./c.example.autotvout_sbu2prt_nw_V_last_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_id_V  "./c.example.autotvout_sbu2prt_nw_V_id_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_user_V  "./c.example.autotvout_sbu2prt_nw_V_user_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_data_V  "./c.example.autotvout_sbu2mlx_V_data_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_keep_V  "./c.example.autotvout_sbu2mlx_V_keep_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_last_V  "./c.example.autotvout_sbu2mlx_V_last_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_id_V  "./c.example.autotvout_sbu2mlx_V_id_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_user_V  "./c.example.autotvout_sbu2mlx_V_user_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_data_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_cx_V_data_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_keep_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_last_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_cx_V_last_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_id_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_cx_V_id_V.dat"
`define AUTOTB_TVOUT_sbu2prt_cx_V_user_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_cx_V_user_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_data_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_nw_V_data_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_keep_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_last_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_nw_V_last_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_id_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_nw_V_id_V.dat"
`define AUTOTB_TVOUT_sbu2prt_nw_V_user_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2prt_nw_V_user_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_data_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2mlx_V_data_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_keep_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2mlx_V_keep_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_last_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2mlx_V_last_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_id_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2mlx_V_id_V.dat"
`define AUTOTB_TVOUT_sbu2mlx_V_user_V_out_wrapc  "./impl_rtl.example.autotvout_sbu2mlx_V_user_V.dat"
module `AUTOTB_TOP;

parameter AUTOTB_TRANSACTION_NUM = 218;
parameter PROGRESS_TIMEOUT = 10000000;
parameter LATENCY_ESTIMATION = 4390;
parameter LENGTH_prt_nw2sbu_V_data_V = 1;
parameter LENGTH_prt_nw2sbu_V_keep_V = 1;
parameter LENGTH_prt_nw2sbu_V_last_V = 1;
parameter LENGTH_prt_nw2sbu_V_id_V = 1;
parameter LENGTH_prt_nw2sbu_V_user_V = 1;
parameter LENGTH_prt_cx2sbu_V_data_V = 0;
parameter LENGTH_prt_cx2sbu_V_keep_V = 0;
parameter LENGTH_prt_cx2sbu_V_last_V = 0;
parameter LENGTH_prt_cx2sbu_V_id_V = 0;
parameter LENGTH_prt_cx2sbu_V_user_V = 0;
parameter LENGTH_mlx2sbu_V_data_V = 0;
parameter LENGTH_mlx2sbu_V_keep_V = 0;
parameter LENGTH_mlx2sbu_V_last_V = 0;
parameter LENGTH_mlx2sbu_V_id_V = 0;
parameter LENGTH_mlx2sbu_V_user_V = 0;
parameter LENGTH_sbu2prt_cx_V_data_V = 0;
parameter LENGTH_sbu2prt_cx_V_keep_V = 0;
parameter LENGTH_sbu2prt_cx_V_last_V = 0;
parameter LENGTH_sbu2prt_cx_V_id_V = 0;
parameter LENGTH_sbu2prt_cx_V_user_V = 0;
parameter LENGTH_sbu2prt_nw_V_data_V = 2;
parameter LENGTH_sbu2prt_nw_V_keep_V = 2;
parameter LENGTH_sbu2prt_nw_V_last_V = 2;
parameter LENGTH_sbu2prt_nw_V_id_V = 2;
parameter LENGTH_sbu2prt_nw_V_user_V = 2;
parameter LENGTH_sbu2mlx_V_data_V = 0;
parameter LENGTH_sbu2mlx_V_keep_V = 0;
parameter LENGTH_sbu2mlx_V_last_V = 0;
parameter LENGTH_sbu2mlx_V_id_V = 0;
parameter LENGTH_sbu2mlx_V_user_V = 0;

task read_token;
    input integer fp;
    output reg [535 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end
endtask

task post_check;
    input integer fp1;
    input integer fp2;
    reg [535 : 0] token1;
    reg [535 : 0] token2;
    reg [535 : 0] golden;
    reg [535 : 0] result;
    integer ret;
    begin
        read_token(fp1, token1);
        read_token(fp2, token2);
        if (token1 != "[[[runtime]]]" || token2 != "[[[runtime]]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
            $finish;
        end
        read_token(fp1, token1);
        read_token(fp2, token2);
        while (token1 != "[[[/runtime]]]" && token2 != "[[[/runtime]]]") begin
            if (token1 != "[[transaction]]" || token2 != "[[transaction]]") begin
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
            end
            read_token(fp1, token1);  // skip transaction number
            read_token(fp2, token2);  // skip transaction number
              read_token(fp1, token1);
              read_token(fp2, token2);
            while(token1 != "[[/transaction]]" && token2 != "[[/transaction]]") begin
                ret = $sscanf(token1, "0x%x", golden);
                  if (ret != 1) begin
                      $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                  end
                ret = $sscanf(token2, "0x%x", result);
                  if (ret != 1) begin
                      $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                  end
                if(golden != result) begin
                      $display("%x (expected) vs. %x (actual) - mismatch", golden, result);
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                end
                  read_token(fp1, token1);
                  read_token(fp2, token2);
            end
              read_token(fp1, token1);
              read_token(fp2, token2);
        end
    end
endtask

reg AESL_clock;
reg rst;
reg start;
reg ce;
reg tb_continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
wire [255 : 0] prt_nw2sbu_TDATA;
wire [31 : 0] prt_nw2sbu_TKEEP;
wire [0 : 0] prt_nw2sbu_TLAST;
wire [2 : 0] prt_nw2sbu_TID;
wire [11 : 0] prt_nw2sbu_TUSER;
wire [255 : 0] prt_cx2sbu_TDATA;
wire [31 : 0] prt_cx2sbu_TKEEP;
wire [0 : 0] prt_cx2sbu_TLAST;
wire [2 : 0] prt_cx2sbu_TID;
wire [11 : 0] prt_cx2sbu_TUSER;
wire [255 : 0] mlx2sbu_TDATA;
wire [31 : 0] mlx2sbu_TKEEP;
wire [0 : 0] mlx2sbu_TLAST;
wire [2 : 0] mlx2sbu_TID;
wire [11 : 0] mlx2sbu_TUSER;
wire [255 : 0] sbu2prt_cx_TDATA;
wire [31 : 0] sbu2prt_cx_TKEEP;
wire [0 : 0] sbu2prt_cx_TLAST;
wire [2 : 0] sbu2prt_cx_TID;
wire [11 : 0] sbu2prt_cx_TUSER;
wire [255 : 0] sbu2prt_nw_TDATA;
wire [31 : 0] sbu2prt_nw_TKEEP;
wire [0 : 0] sbu2prt_nw_TLAST;
wire [2 : 0] sbu2prt_nw_TID;
wire [11 : 0] sbu2prt_nw_TUSER;
wire [255 : 0] sbu2mlx_TDATA;
wire [31 : 0] sbu2mlx_TKEEP;
wire [0 : 0] sbu2mlx_TLAST;
wire [2 : 0] sbu2mlx_TID;
wire [11 : 0] sbu2mlx_TUSER;
wire  prt_nw2sbu_TVALID;
wire  prt_nw2sbu_TREADY;
wire  prt_cx2sbu_TVALID;
wire  prt_cx2sbu_TREADY;
wire  sbu2prt_nw_TVALID;
wire  sbu2prt_nw_TREADY;
wire  mlx2sbu_TVALID;
wire  mlx2sbu_TREADY;
wire  sbu2mlx_TVALID;
wire  sbu2mlx_TREADY;
wire  sbu2prt_cx_TVALID;
wire  sbu2prt_cx_TREADY;
wire ap_done;
wire ap_start;
wire ap_ready;
wire ap_idle;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;

wire ap_clk;
wire ap_rst_n;
wire ap_rst_n_n;

`AUTOTB_DUT `AUTOTB_DUT_INST(
    .prt_nw2sbu_TDATA(prt_nw2sbu_TDATA),
    .prt_nw2sbu_TKEEP(prt_nw2sbu_TKEEP),
    .prt_nw2sbu_TLAST(prt_nw2sbu_TLAST),
    .prt_nw2sbu_TID(prt_nw2sbu_TID),
    .prt_nw2sbu_TUSER(prt_nw2sbu_TUSER),
    .prt_cx2sbu_TDATA(prt_cx2sbu_TDATA),
    .prt_cx2sbu_TKEEP(prt_cx2sbu_TKEEP),
    .prt_cx2sbu_TLAST(prt_cx2sbu_TLAST),
    .prt_cx2sbu_TID(prt_cx2sbu_TID),
    .prt_cx2sbu_TUSER(prt_cx2sbu_TUSER),
    .mlx2sbu_TDATA(mlx2sbu_TDATA),
    .mlx2sbu_TKEEP(mlx2sbu_TKEEP),
    .mlx2sbu_TLAST(mlx2sbu_TLAST),
    .mlx2sbu_TID(mlx2sbu_TID),
    .mlx2sbu_TUSER(mlx2sbu_TUSER),
    .sbu2prt_cx_TDATA(sbu2prt_cx_TDATA),
    .sbu2prt_cx_TKEEP(sbu2prt_cx_TKEEP),
    .sbu2prt_cx_TLAST(sbu2prt_cx_TLAST),
    .sbu2prt_cx_TID(sbu2prt_cx_TID),
    .sbu2prt_cx_TUSER(sbu2prt_cx_TUSER),
    .sbu2prt_nw_TDATA(sbu2prt_nw_TDATA),
    .sbu2prt_nw_TKEEP(sbu2prt_nw_TKEEP),
    .sbu2prt_nw_TLAST(sbu2prt_nw_TLAST),
    .sbu2prt_nw_TID(sbu2prt_nw_TID),
    .sbu2prt_nw_TUSER(sbu2prt_nw_TUSER),
    .sbu2mlx_TDATA(sbu2mlx_TDATA),
    .sbu2mlx_TKEEP(sbu2mlx_TKEEP),
    .sbu2mlx_TLAST(sbu2mlx_TLAST),
    .sbu2mlx_TID(sbu2mlx_TID),
    .sbu2mlx_TUSER(sbu2mlx_TUSER),
    .ap_clk(ap_clk),
    .ap_rst_n(ap_rst_n),
    .prt_nw2sbu_TVALID(prt_nw2sbu_TVALID),
    .prt_nw2sbu_TREADY(prt_nw2sbu_TREADY),
    .prt_cx2sbu_TVALID(prt_cx2sbu_TVALID),
    .prt_cx2sbu_TREADY(prt_cx2sbu_TREADY),
    .sbu2prt_nw_TVALID(sbu2prt_nw_TVALID),
    .sbu2prt_nw_TREADY(sbu2prt_nw_TREADY),
    .mlx2sbu_TVALID(mlx2sbu_TVALID),
    .mlx2sbu_TREADY(mlx2sbu_TREADY),
    .sbu2mlx_TVALID(sbu2mlx_TVALID),
    .sbu2mlx_TREADY(sbu2mlx_TREADY),
    .sbu2prt_cx_TVALID(sbu2prt_cx_TVALID),
    .sbu2prt_cx_TREADY(sbu2prt_cx_TREADY),
    .ap_done(ap_done),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_idle(ap_idle));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst_n = AESL_reset;
assign ap_rst_n_n = ~AESL_reset;
assign AESL_reset = rst;
assign AESL_done = ap_done;
assign ap_start = AESL_start;
assign AESL_start = start;
assign AESL_ready = ap_ready;
assign AESL_idle = ap_idle;
assign AESL_ce = ce;
assign AESL_continue = tb_continue;
    always @(posedge AESL_clock) begin
        if (AESL_reset === 0) begin
        end else begin
            if (AESL_done !== 1 && AESL_done !== 0) begin
                $display("ERROR: Control signal AESL_done is invalid!");
                $finish;
            end
        end
    end
    always @(posedge AESL_clock) begin
        if (AESL_reset === 0) begin
        end else begin
            if (AESL_ready !== 1 && AESL_ready !== 0) begin
                $display("ERROR: Control signal AESL_ready is invalid!");
                $finish;
            end
        end
    end






























reg [31:0] ap_c_n_tvin_trans_num_prt_nw2sbu_V_data_V;

reg prt_nw2sbu_ready_reg; // for self-sync

wire prt_nw2sbu_ready;
wire prt_nw2sbu_done;
wire [31:0] prt_nw2sbu_transaction;
wire axi_s_prt_nw2sbu_TVALID;
wire axi_s_prt_nw2sbu_TREADY;

AESL_axi_s_prt_nw2sbu AESL_AXI_S_prt_nw2sbu(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_prt_nw2sbu_TDATA(prt_nw2sbu_TDATA),
    .TRAN_prt_nw2sbu_TKEEP(prt_nw2sbu_TKEEP),
    .TRAN_prt_nw2sbu_TLAST(prt_nw2sbu_TLAST),
    .TRAN_prt_nw2sbu_TID(prt_nw2sbu_TID),
    .TRAN_prt_nw2sbu_TUSER(prt_nw2sbu_TUSER),
    .TRAN_prt_nw2sbu_TVALID(axi_s_prt_nw2sbu_TVALID),
    .TRAN_prt_nw2sbu_TREADY(axi_s_prt_nw2sbu_TREADY),
    .ready(prt_nw2sbu_ready),
    .done(prt_nw2sbu_done),
    .transaction(prt_nw2sbu_transaction));

assign prt_nw2sbu_ready = ready;
assign prt_nw2sbu_done = 0;

assign prt_nw2sbu_TVALID = axi_s_prt_nw2sbu_TVALID;

assign axi_s_prt_nw2sbu_TREADY = prt_nw2sbu_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_prt_cx2sbu_V_data_V;

reg prt_cx2sbu_ready_reg; // for self-sync

wire prt_cx2sbu_ready;
wire prt_cx2sbu_done;
wire [31:0] prt_cx2sbu_transaction;
wire axi_s_prt_cx2sbu_TVALID;
wire axi_s_prt_cx2sbu_TREADY;

AESL_axi_s_prt_cx2sbu AESL_AXI_S_prt_cx2sbu(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_prt_cx2sbu_TDATA(prt_cx2sbu_TDATA),
    .TRAN_prt_cx2sbu_TKEEP(prt_cx2sbu_TKEEP),
    .TRAN_prt_cx2sbu_TLAST(prt_cx2sbu_TLAST),
    .TRAN_prt_cx2sbu_TID(prt_cx2sbu_TID),
    .TRAN_prt_cx2sbu_TUSER(prt_cx2sbu_TUSER),
    .TRAN_prt_cx2sbu_TVALID(axi_s_prt_cx2sbu_TVALID),
    .TRAN_prt_cx2sbu_TREADY(axi_s_prt_cx2sbu_TREADY),
    .ready(prt_cx2sbu_ready),
    .done(prt_cx2sbu_done),
    .transaction(prt_cx2sbu_transaction));

assign prt_cx2sbu_ready = ready;
assign prt_cx2sbu_done = 0;

assign prt_cx2sbu_TVALID = axi_s_prt_cx2sbu_TVALID;

assign axi_s_prt_cx2sbu_TREADY = prt_cx2sbu_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_mlx2sbu_V_data_V;

reg mlx2sbu_ready_reg; // for self-sync

wire mlx2sbu_ready;
wire mlx2sbu_done;
wire [31:0] mlx2sbu_transaction;
wire axi_s_mlx2sbu_TVALID;
wire axi_s_mlx2sbu_TREADY;

AESL_axi_s_mlx2sbu AESL_AXI_S_mlx2sbu(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_mlx2sbu_TDATA(mlx2sbu_TDATA),
    .TRAN_mlx2sbu_TKEEP(mlx2sbu_TKEEP),
    .TRAN_mlx2sbu_TLAST(mlx2sbu_TLAST),
    .TRAN_mlx2sbu_TID(mlx2sbu_TID),
    .TRAN_mlx2sbu_TUSER(mlx2sbu_TUSER),
    .TRAN_mlx2sbu_TVALID(axi_s_mlx2sbu_TVALID),
    .TRAN_mlx2sbu_TREADY(axi_s_mlx2sbu_TREADY),
    .ready(mlx2sbu_ready),
    .done(mlx2sbu_done),
    .transaction(mlx2sbu_transaction));

assign mlx2sbu_ready = ready;
assign mlx2sbu_done = 0;

assign mlx2sbu_TVALID = axi_s_mlx2sbu_TVALID;

assign axi_s_mlx2sbu_TREADY = mlx2sbu_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_sbu2prt_cx_V_data_V;

reg sbu2prt_cx_ready_reg; // for self-sync

wire sbu2prt_cx_ready;
wire sbu2prt_cx_done;
wire [31:0] sbu2prt_cx_transaction;
wire axi_s_sbu2prt_cx_TVALID;
wire axi_s_sbu2prt_cx_TREADY;

AESL_axi_s_sbu2prt_cx AESL_AXI_S_sbu2prt_cx(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_sbu2prt_cx_TDATA(sbu2prt_cx_TDATA),
    .TRAN_sbu2prt_cx_TKEEP(sbu2prt_cx_TKEEP),
    .TRAN_sbu2prt_cx_TLAST(sbu2prt_cx_TLAST),
    .TRAN_sbu2prt_cx_TID(sbu2prt_cx_TID),
    .TRAN_sbu2prt_cx_TUSER(sbu2prt_cx_TUSER),
    .TRAN_sbu2prt_cx_TVALID(axi_s_sbu2prt_cx_TVALID),
    .TRAN_sbu2prt_cx_TREADY(axi_s_sbu2prt_cx_TREADY),
    .ready(sbu2prt_cx_ready),
    .done(sbu2prt_cx_done),
    .transaction(sbu2prt_cx_transaction));

assign sbu2prt_cx_ready = 0;
assign sbu2prt_cx_done = AESL_done;

assign axi_s_sbu2prt_cx_TVALID = sbu2prt_cx_TVALID;

reg reg_sbu2prt_cx_TREADY;
initial begin : gen_reg_sbu2prt_cx_TREADY_process
    integer proc_rand;
    reg_sbu2prt_cx_TREADY = 0;
    while(1)
    begin
        @(axi_s_sbu2prt_cx_TREADY);
        reg_sbu2prt_cx_TREADY = axi_s_sbu2prt_cx_TREADY;
    end
end


assign sbu2prt_cx_TREADY = reg_sbu2prt_cx_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_sbu2prt_nw_V_data_V;

reg sbu2prt_nw_ready_reg; // for self-sync

wire sbu2prt_nw_ready;
wire sbu2prt_nw_done;
wire [31:0] sbu2prt_nw_transaction;
wire axi_s_sbu2prt_nw_TVALID;
wire axi_s_sbu2prt_nw_TREADY;

AESL_axi_s_sbu2prt_nw AESL_AXI_S_sbu2prt_nw(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_sbu2prt_nw_TDATA(sbu2prt_nw_TDATA),
    .TRAN_sbu2prt_nw_TKEEP(sbu2prt_nw_TKEEP),
    .TRAN_sbu2prt_nw_TLAST(sbu2prt_nw_TLAST),
    .TRAN_sbu2prt_nw_TID(sbu2prt_nw_TID),
    .TRAN_sbu2prt_nw_TUSER(sbu2prt_nw_TUSER),
    .TRAN_sbu2prt_nw_TVALID(axi_s_sbu2prt_nw_TVALID),
    .TRAN_sbu2prt_nw_TREADY(axi_s_sbu2prt_nw_TREADY),
    .ready(sbu2prt_nw_ready),
    .done(sbu2prt_nw_done),
    .transaction(sbu2prt_nw_transaction));

assign sbu2prt_nw_ready = 0;
assign sbu2prt_nw_done = AESL_done;

assign axi_s_sbu2prt_nw_TVALID = sbu2prt_nw_TVALID;

reg reg_sbu2prt_nw_TREADY;
initial begin : gen_reg_sbu2prt_nw_TREADY_process
    integer proc_rand;
    reg_sbu2prt_nw_TREADY = 0;
    while(1)
    begin
        @(axi_s_sbu2prt_nw_TREADY);
        reg_sbu2prt_nw_TREADY = axi_s_sbu2prt_nw_TREADY;
    end
end


assign sbu2prt_nw_TREADY = reg_sbu2prt_nw_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_sbu2mlx_V_data_V;

reg sbu2mlx_ready_reg; // for self-sync

wire sbu2mlx_ready;
wire sbu2mlx_done;
wire [31:0] sbu2mlx_transaction;
wire axi_s_sbu2mlx_TVALID;
wire axi_s_sbu2mlx_TREADY;

AESL_axi_s_sbu2mlx AESL_AXI_S_sbu2mlx(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_sbu2mlx_TDATA(sbu2mlx_TDATA),
    .TRAN_sbu2mlx_TKEEP(sbu2mlx_TKEEP),
    .TRAN_sbu2mlx_TLAST(sbu2mlx_TLAST),
    .TRAN_sbu2mlx_TID(sbu2mlx_TID),
    .TRAN_sbu2mlx_TUSER(sbu2mlx_TUSER),
    .TRAN_sbu2mlx_TVALID(axi_s_sbu2mlx_TVALID),
    .TRAN_sbu2mlx_TREADY(axi_s_sbu2mlx_TREADY),
    .ready(sbu2mlx_ready),
    .done(sbu2mlx_done),
    .transaction(sbu2mlx_transaction));

assign sbu2mlx_ready = 0;
assign sbu2mlx_done = AESL_done;

assign axi_s_sbu2mlx_TVALID = sbu2mlx_TVALID;

reg reg_sbu2mlx_TREADY;
initial begin : gen_reg_sbu2mlx_TREADY_process
    integer proc_rand;
    reg_sbu2mlx_TREADY = 0;
    while(1)
    begin
        @(axi_s_sbu2mlx_TREADY);
        reg_sbu2mlx_TREADY = axi_s_sbu2mlx_TREADY;
    end
end


assign sbu2mlx_TREADY = reg_sbu2mlx_TREADY;

initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 1);
    while(AESL_ready_cnt != AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

    event next_trigger_ready_cnt;
    
    initial begin : gen_ready_cnt
        ready_cnt = 0;
        wait (AESL_reset === 1);
        forever begin
            @ (posedge AESL_clock);
            if (ready == 1) begin
                if (ready_cnt < AUTOTB_TRANSACTION_NUM) begin
                    ready_cnt = ready_cnt + 1;
                end
            end
            -> next_trigger_ready_cnt;
        end
    end
    
    wire all_finish = (done_cnt == AUTOTB_TRANSACTION_NUM);
    
    // done_cnt
    always @ (posedge AESL_clock) begin
        if (~AESL_reset) begin
            done_cnt <= 0;
        end else begin
            if (AESL_done == 1) begin
                if (done_cnt < AUTOTB_TRANSACTION_NUM) begin
                    done_cnt <= done_cnt + 1;
                end
            end
        end
    end
    
    initial begin : finish_simulation
        integer fp1;
        integer fp2;
        wait (all_finish == 1);
        // last transaction is saved at negedge right after last done
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_cx_V_data_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_cx_V_data_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_cx_V_data_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_cx_V_data_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_cx_V_data_V.dat with impl_rtl.example.autotvout_sbu2prt_cx_V_data_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat with impl_rtl.example.autotvout_sbu2prt_cx_V_keep_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_cx_V_last_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_cx_V_last_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_cx_V_last_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_cx_V_last_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_cx_V_last_V.dat with impl_rtl.example.autotvout_sbu2prt_cx_V_last_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_cx_V_id_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_cx_V_id_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_cx_V_id_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_cx_V_id_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_cx_V_id_V.dat with impl_rtl.example.autotvout_sbu2prt_cx_V_id_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_cx_V_user_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_cx_V_user_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_cx_V_user_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_cx_V_user_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_cx_V_user_V.dat with impl_rtl.example.autotvout_sbu2prt_cx_V_user_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_nw_V_data_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_nw_V_data_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_nw_V_data_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_nw_V_data_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_nw_V_data_V.dat with impl_rtl.example.autotvout_sbu2prt_nw_V_data_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat with impl_rtl.example.autotvout_sbu2prt_nw_V_keep_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_nw_V_last_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_nw_V_last_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_nw_V_last_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_nw_V_last_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_nw_V_last_V.dat with impl_rtl.example.autotvout_sbu2prt_nw_V_last_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_nw_V_id_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_nw_V_id_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_nw_V_id_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_nw_V_id_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_nw_V_id_V.dat with impl_rtl.example.autotvout_sbu2prt_nw_V_id_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2prt_nw_V_user_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2prt_nw_V_user_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2prt_nw_V_user_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2prt_nw_V_user_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2prt_nw_V_user_V.dat with impl_rtl.example.autotvout_sbu2prt_nw_V_user_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2mlx_V_data_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2mlx_V_data_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2mlx_V_data_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2mlx_V_data_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2mlx_V_data_V.dat with impl_rtl.example.autotvout_sbu2mlx_V_data_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2mlx_V_keep_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2mlx_V_keep_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2mlx_V_keep_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2mlx_V_keep_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2mlx_V_keep_V.dat with impl_rtl.example.autotvout_sbu2mlx_V_keep_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2mlx_V_last_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2mlx_V_last_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2mlx_V_last_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2mlx_V_last_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2mlx_V_last_V.dat with impl_rtl.example.autotvout_sbu2mlx_V_last_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2mlx_V_id_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2mlx_V_id_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2mlx_V_id_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2mlx_V_id_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2mlx_V_id_V.dat with impl_rtl.example.autotvout_sbu2mlx_V_id_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
    fp1 = $fopen("./rtl.example.autotvout_sbu2mlx_V_user_V.dat", "r");
    fp2 = $fopen("./impl_rtl.example.autotvout_sbu2mlx_V_user_V.dat", "r");
    if(fp1 == 0)        // Failed to open file
        $display("Failed to open file \"./rtl.example.autotvout_sbu2mlx_V_user_V.dat\"!");
    else if(fp2 == 0)
        $display("Failed to open file \"./impl_rtl.example.autotvout_sbu2mlx_V_user_V.dat\"!");
    else begin
        $display("Comparing rtl.example.autotvout_sbu2mlx_V_user_V.dat with impl_rtl.example.autotvout_sbu2mlx_V_user_V.dat");
        post_check(fp1, fp2);
    end
    $fclose(fp1);
    $fclose(fp2);
        $display("Simulation Passed.");
        $finish;
    end
    
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end


reg end_prt_nw2sbu_V_data_V;
reg [31:0] size_prt_nw2sbu_V_data_V;
reg [31:0] size_prt_nw2sbu_V_data_V_backup;
reg end_prt_nw2sbu_V_keep_V;
reg [31:0] size_prt_nw2sbu_V_keep_V;
reg [31:0] size_prt_nw2sbu_V_keep_V_backup;
reg end_prt_nw2sbu_V_last_V;
reg [31:0] size_prt_nw2sbu_V_last_V;
reg [31:0] size_prt_nw2sbu_V_last_V_backup;
reg end_prt_nw2sbu_V_id_V;
reg [31:0] size_prt_nw2sbu_V_id_V;
reg [31:0] size_prt_nw2sbu_V_id_V_backup;
reg end_prt_nw2sbu_V_user_V;
reg [31:0] size_prt_nw2sbu_V_user_V;
reg [31:0] size_prt_nw2sbu_V_user_V_backup;
reg end_prt_cx2sbu_V_data_V;
reg [31:0] size_prt_cx2sbu_V_data_V;
reg [31:0] size_prt_cx2sbu_V_data_V_backup;
reg end_prt_cx2sbu_V_keep_V;
reg [31:0] size_prt_cx2sbu_V_keep_V;
reg [31:0] size_prt_cx2sbu_V_keep_V_backup;
reg end_prt_cx2sbu_V_last_V;
reg [31:0] size_prt_cx2sbu_V_last_V;
reg [31:0] size_prt_cx2sbu_V_last_V_backup;
reg end_prt_cx2sbu_V_id_V;
reg [31:0] size_prt_cx2sbu_V_id_V;
reg [31:0] size_prt_cx2sbu_V_id_V_backup;
reg end_prt_cx2sbu_V_user_V;
reg [31:0] size_prt_cx2sbu_V_user_V;
reg [31:0] size_prt_cx2sbu_V_user_V_backup;
reg end_mlx2sbu_V_data_V;
reg [31:0] size_mlx2sbu_V_data_V;
reg [31:0] size_mlx2sbu_V_data_V_backup;
reg end_mlx2sbu_V_keep_V;
reg [31:0] size_mlx2sbu_V_keep_V;
reg [31:0] size_mlx2sbu_V_keep_V_backup;
reg end_mlx2sbu_V_last_V;
reg [31:0] size_mlx2sbu_V_last_V;
reg [31:0] size_mlx2sbu_V_last_V_backup;
reg end_mlx2sbu_V_id_V;
reg [31:0] size_mlx2sbu_V_id_V;
reg [31:0] size_mlx2sbu_V_id_V_backup;
reg end_mlx2sbu_V_user_V;
reg [31:0] size_mlx2sbu_V_user_V;
reg [31:0] size_mlx2sbu_V_user_V_backup;
reg end_sbu2prt_cx_V_data_V;
reg [31:0] size_sbu2prt_cx_V_data_V;
reg [31:0] size_sbu2prt_cx_V_data_V_backup;
reg end_sbu2prt_cx_V_keep_V;
reg [31:0] size_sbu2prt_cx_V_keep_V;
reg [31:0] size_sbu2prt_cx_V_keep_V_backup;
reg end_sbu2prt_cx_V_last_V;
reg [31:0] size_sbu2prt_cx_V_last_V;
reg [31:0] size_sbu2prt_cx_V_last_V_backup;
reg end_sbu2prt_cx_V_id_V;
reg [31:0] size_sbu2prt_cx_V_id_V;
reg [31:0] size_sbu2prt_cx_V_id_V_backup;
reg end_sbu2prt_cx_V_user_V;
reg [31:0] size_sbu2prt_cx_V_user_V;
reg [31:0] size_sbu2prt_cx_V_user_V_backup;
reg end_sbu2prt_nw_V_data_V;
reg [31:0] size_sbu2prt_nw_V_data_V;
reg [31:0] size_sbu2prt_nw_V_data_V_backup;
reg end_sbu2prt_nw_V_keep_V;
reg [31:0] size_sbu2prt_nw_V_keep_V;
reg [31:0] size_sbu2prt_nw_V_keep_V_backup;
reg end_sbu2prt_nw_V_last_V;
reg [31:0] size_sbu2prt_nw_V_last_V;
reg [31:0] size_sbu2prt_nw_V_last_V_backup;
reg end_sbu2prt_nw_V_id_V;
reg [31:0] size_sbu2prt_nw_V_id_V;
reg [31:0] size_sbu2prt_nw_V_id_V_backup;
reg end_sbu2prt_nw_V_user_V;
reg [31:0] size_sbu2prt_nw_V_user_V;
reg [31:0] size_sbu2prt_nw_V_user_V_backup;
reg end_sbu2mlx_V_data_V;
reg [31:0] size_sbu2mlx_V_data_V;
reg [31:0] size_sbu2mlx_V_data_V_backup;
reg end_sbu2mlx_V_keep_V;
reg [31:0] size_sbu2mlx_V_keep_V;
reg [31:0] size_sbu2mlx_V_keep_V_backup;
reg end_sbu2mlx_V_last_V;
reg [31:0] size_sbu2mlx_V_last_V;
reg [31:0] size_sbu2mlx_V_last_V_backup;
reg end_sbu2mlx_V_id_V;
reg [31:0] size_sbu2mlx_V_id_V;
reg [31:0] size_sbu2mlx_V_id_V_backup;
reg end_sbu2mlx_V_user_V;
reg [31:0] size_sbu2mlx_V_user_V;
reg [31:0] size_sbu2mlx_V_user_V_backup;

initial begin : initial_process
    integer proc_rand;
    rst = 0;
    # 100;
    repeat(3) @ (posedge AESL_clock);
    rst = 1;
end
initial begin : start_process
    integer proc_rand;
    reg [31:0] start_cnt;
    ce = 1;
    start = 0;
    start_cnt = 0;
    wait (AESL_reset === 1);
    @ (posedge AESL_clock);
    #0 start = 1;
    start_cnt = start_cnt + 1;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt >= AUTOTB_TRANSACTION_NUM) begin
            // keep pushing garbage in
            #0 start = 1;
        end
        if (AESL_ready) begin
            start_cnt = start_cnt + 1;
        end
    end
end

always @(AESL_done)
begin
    tb_continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end

reg dump_tvout_finish_sbu2prt_cx_V_data_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_cx_V_data_V
    integer fp;
    dump_tvout_finish_sbu2prt_cx_V_data_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_data_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_data_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_cx_V_data_V = 1;
end


reg dump_tvout_finish_sbu2prt_cx_V_keep_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_cx_V_keep_V
    integer fp;
    dump_tvout_finish_sbu2prt_cx_V_keep_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_keep_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_keep_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_cx_V_keep_V = 1;
end


reg dump_tvout_finish_sbu2prt_cx_V_last_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_cx_V_last_V
    integer fp;
    dump_tvout_finish_sbu2prt_cx_V_last_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_last_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_last_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_cx_V_last_V = 1;
end


reg dump_tvout_finish_sbu2prt_cx_V_id_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_cx_V_id_V
    integer fp;
    dump_tvout_finish_sbu2prt_cx_V_id_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_id_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_id_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_cx_V_id_V = 1;
end


reg dump_tvout_finish_sbu2prt_cx_V_user_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_cx_V_user_V
    integer fp;
    dump_tvout_finish_sbu2prt_cx_V_user_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_user_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_cx_V_user_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_cx_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_cx_V_user_V = 1;
end


reg dump_tvout_finish_sbu2prt_nw_V_data_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_nw_V_data_V
    integer fp;
    dump_tvout_finish_sbu2prt_nw_V_data_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_data_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_data_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_nw_V_data_V = 1;
end


reg dump_tvout_finish_sbu2prt_nw_V_keep_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_nw_V_keep_V
    integer fp;
    dump_tvout_finish_sbu2prt_nw_V_keep_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_keep_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_keep_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_nw_V_keep_V = 1;
end


reg dump_tvout_finish_sbu2prt_nw_V_last_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_nw_V_last_V
    integer fp;
    dump_tvout_finish_sbu2prt_nw_V_last_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_last_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_last_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_nw_V_last_V = 1;
end


reg dump_tvout_finish_sbu2prt_nw_V_id_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_nw_V_id_V
    integer fp;
    dump_tvout_finish_sbu2prt_nw_V_id_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_id_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_id_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_nw_V_id_V = 1;
end


reg dump_tvout_finish_sbu2prt_nw_V_user_V;

initial begin : dump_tvout_runtime_sign_sbu2prt_nw_V_user_V
    integer fp;
    dump_tvout_finish_sbu2prt_nw_V_user_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_user_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2prt_nw_V_user_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2prt_nw_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2prt_nw_V_user_V = 1;
end


reg dump_tvout_finish_sbu2mlx_V_data_V;

initial begin : dump_tvout_runtime_sign_sbu2mlx_V_data_V
    integer fp;
    dump_tvout_finish_sbu2mlx_V_data_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_data_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_data_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_data_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2mlx_V_data_V = 1;
end


reg dump_tvout_finish_sbu2mlx_V_keep_V;

initial begin : dump_tvout_runtime_sign_sbu2mlx_V_keep_V
    integer fp;
    dump_tvout_finish_sbu2mlx_V_keep_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_keep_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_keep_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_keep_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2mlx_V_keep_V = 1;
end


reg dump_tvout_finish_sbu2mlx_V_last_V;

initial begin : dump_tvout_runtime_sign_sbu2mlx_V_last_V
    integer fp;
    dump_tvout_finish_sbu2mlx_V_last_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_last_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_last_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_last_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2mlx_V_last_V = 1;
end


reg dump_tvout_finish_sbu2mlx_V_id_V;

initial begin : dump_tvout_runtime_sign_sbu2mlx_V_id_V
    integer fp;
    dump_tvout_finish_sbu2mlx_V_id_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_id_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_id_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_id_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2mlx_V_id_V = 1;
end


reg dump_tvout_finish_sbu2mlx_V_user_V;

initial begin : dump_tvout_runtime_sign_sbu2mlx_V_user_V
    integer fp;
    dump_tvout_finish_sbu2mlx_V_user_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_user_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_sbu2mlx_V_user_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_sbu2mlx_V_user_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_sbu2mlx_V_user_V = 1;
end


////////////////////////////////////////////
// progress and performance
////////////////////////////////////////////

task wait_start();
    while (~AESL_start) begin
        @ (posedge AESL_clock);
    end
endtask

reg [31:0] clk_cnt = 0;
reg AESL_ready_p1;

always @ (posedge AESL_clock) begin
    clk_cnt <= clk_cnt + 1;
    AESL_ready_p1 <= AESL_ready;
end

reg [31:0] start_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] start_cnt;
reg [31:0] finish_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] finish_cnt;
event report_progress;

initial begin
    start_cnt = 0;
    finish_cnt = 0;
    wait (AESL_reset == 1);
    wait_start();
    start_timestamp[start_cnt] = clk_cnt;
    start_cnt = start_cnt + 1;
    if (AESL_done) begin
        finish_timestamp[finish_cnt] = clk_cnt;
        finish_cnt = finish_cnt + 1;
    end
    -> report_progress;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_start && AESL_ready_p1) begin
                start_timestamp[start_cnt] = clk_cnt;
                start_cnt = start_cnt + 1;
            end
        end
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                finish_timestamp[finish_cnt] = clk_cnt;
                finish_cnt = finish_cnt + 1;
            end
        end
        -> report_progress;
    end
end

reg [31:0] progress_timeout;

initial begin : simulation_progress
    real intra_progress;
    wait (AESL_reset == 1);
    progress_timeout = PROGRESS_TIMEOUT;
    $display("////////////////////////////////////////////////////////////////////////////////////");
    $display("// Inter-Transaction Progress: Completed Transaction / Total Transaction");
    $display("// Intra-Transaction Progress: Measured Latency / Latency Estimation * 100%%");
    $display("//");
    $display("// RTL Simulation : \"Inter-Transaction Progress\" [\"Intra-Transaction Progress\"] @ \"Simulation Time\"");
    $display("////////////////////////////////////////////////////////////////////////////////////");
    print_progress();
    while (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
        @ (report_progress);
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                print_progress();
                progress_timeout = PROGRESS_TIMEOUT;
            end else begin
                if (progress_timeout == 0) begin
                    print_progress();
                    progress_timeout = PROGRESS_TIMEOUT;
                end else begin
                    progress_timeout = progress_timeout - 1;
                end
            end
        end
    end
    print_progress();
    $display("////////////////////////////////////////////////////////////////////////////////////");
    calculate_performance();
end

task get_intra_progress(output real intra_progress);
    begin
        if (start_cnt > finish_cnt) begin
            intra_progress = clk_cnt - start_timestamp[finish_cnt];
        end else begin
            intra_progress = 0;
        end
        intra_progress = intra_progress / LATENCY_ESTIMATION;
    end
endtask

task print_progress();
    real intra_progress;
    begin
        if (LATENCY_ESTIMATION > 0) begin
            get_intra_progress(intra_progress);
            $display("// RTL Simulation : %0d / %0d [%2.2f%%] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, intra_progress * 100, $time);
        end else begin
            $display("// RTL Simulation : %0d / %0d [n/a] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, $time);
        end
    end
endtask

task calculate_performance();
    integer i;
    integer fp;
    reg [31:0] latency [0:AUTOTB_TRANSACTION_NUM - 1];
    reg [31:0] latency_min;
    reg [31:0] latency_max;
    reg [31:0] latency_total;
    reg [31:0] latency_average;
    reg [31:0] interval [0:AUTOTB_TRANSACTION_NUM - 2];
    reg [31:0] interval_min;
    reg [31:0] interval_max;
    reg [31:0] interval_total;
    reg [31:0] interval_average;
    begin
        latency_min = -1;
        latency_max = 0;
        latency_total = 0;
        interval_min = -1;
        interval_max = 0;
        interval_total = 0;

        for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
            // calculate latency
            latency[i] = finish_timestamp[i] - start_timestamp[i];
            if (latency[i] > latency_max) latency_max = latency[i];
            if (latency[i] < latency_min) latency_min = latency[i];
            latency_total = latency_total + latency[i];
            // calculate interval
            if (AUTOTB_TRANSACTION_NUM == 1) begin
                interval[i] = 0;
                interval_max = 0;
                interval_min = 0;
                interval_total = 0;
            end else if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                interval[i] = start_timestamp[i + 1] - start_timestamp[i];
                if (interval[i] > interval_max) interval_max = interval[i];
                if (interval[i] < interval_min) interval_min = interval[i];
                interval_total = interval_total + interval[i];
            end
        end

        latency_average = latency_total / AUTOTB_TRANSACTION_NUM;
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            interval_average = 0;
        end else begin
            interval_average = interval_total / (AUTOTB_TRANSACTION_NUM - 1);
        end

        fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

        $fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latency_max);
        $fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latency_min);
        $fdisplay(fp, "$AVER_LATENCY = \"%0d\"", latency_average);
        $fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", interval_max);
        $fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", interval_min);
        $fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", interval_average);

        $fclose(fp);

        fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");

        $fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            i = 0;
            $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
        end else begin
            for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
                if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                    $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
                end else begin
                    $fdisplay(fp, "transaction%8d:%16d               x", i, latency[i]);
                end
            end
        end

        $fclose(fp);
    end
endtask


////////////////////////////////////////////
// Dependence Check
////////////////////////////////////////////

`ifndef POST_SYN

`endif

endmodule
