// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="example,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku060-ffva1156-1l-i,HLS_INPUT_CLOCK=4.600000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.097500,HLS_SYN_LAT=5,HLS_SYN_TPT=6,HLS_SYN_MEM=60,HLS_SYN_DSP=0,HLS_SYN_FF=1862,HLS_SYN_LUT=5145}" *)

module example (
        prt_nw2sbu_TDATA,
        prt_nw2sbu_TKEEP,
        prt_nw2sbu_TLAST,
        prt_nw2sbu_TID,
        prt_nw2sbu_TUSER,
        prt_cx2sbu_TDATA,
        prt_cx2sbu_TKEEP,
        prt_cx2sbu_TLAST,
        prt_cx2sbu_TID,
        prt_cx2sbu_TUSER,
        mlx2sbu_TDATA,
        mlx2sbu_TKEEP,
        mlx2sbu_TLAST,
        mlx2sbu_TID,
        mlx2sbu_TUSER,
        sbu2prt_cx_TDATA,
        sbu2prt_cx_TKEEP,
        sbu2prt_cx_TLAST,
        sbu2prt_cx_TID,
        sbu2prt_cx_TUSER,
        sbu2prt_nw_TDATA,
        sbu2prt_nw_TKEEP,
        sbu2prt_nw_TLAST,
        sbu2prt_nw_TID,
        sbu2prt_nw_TUSER,
        sbu2mlx_TDATA,
        sbu2mlx_TKEEP,
        sbu2mlx_TLAST,
        sbu2mlx_TID,
        sbu2mlx_TUSER,
        ap_clk,
        ap_rst_n,
        prt_nw2sbu_TVALID,
        prt_nw2sbu_TREADY,
        prt_cx2sbu_TVALID,
        prt_cx2sbu_TREADY,
        mlx2sbu_TVALID,
        mlx2sbu_TREADY,
        sbu2mlx_TVALID,
        sbu2mlx_TREADY,
        sbu2prt_nw_TVALID,
        sbu2prt_nw_TREADY,
        sbu2prt_cx_TVALID,
        sbu2prt_cx_TREADY,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);

parameter    ap_const_lv256_lc_1 = 256'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv12_0 = 12'b000000000000;

input  [255:0] prt_nw2sbu_TDATA;
input  [31:0] prt_nw2sbu_TKEEP;
input  [0:0] prt_nw2sbu_TLAST;
input  [2:0] prt_nw2sbu_TID;
input  [11:0] prt_nw2sbu_TUSER;
input  [255:0] prt_cx2sbu_TDATA;
input  [31:0] prt_cx2sbu_TKEEP;
input  [0:0] prt_cx2sbu_TLAST;
input  [2:0] prt_cx2sbu_TID;
input  [11:0] prt_cx2sbu_TUSER;
input  [255:0] mlx2sbu_TDATA;
input  [31:0] mlx2sbu_TKEEP;
input  [0:0] mlx2sbu_TLAST;
input  [2:0] mlx2sbu_TID;
input  [11:0] mlx2sbu_TUSER;
output  [255:0] sbu2prt_cx_TDATA;
output  [31:0] sbu2prt_cx_TKEEP;
output  [0:0] sbu2prt_cx_TLAST;
output  [2:0] sbu2prt_cx_TID;
output  [11:0] sbu2prt_cx_TUSER;
output  [255:0] sbu2prt_nw_TDATA;
output  [31:0] sbu2prt_nw_TKEEP;
output  [0:0] sbu2prt_nw_TLAST;
output  [2:0] sbu2prt_nw_TID;
output  [11:0] sbu2prt_nw_TUSER;
output  [255:0] sbu2mlx_TDATA;
output  [31:0] sbu2mlx_TKEEP;
output  [0:0] sbu2mlx_TLAST;
output  [2:0] sbu2mlx_TID;
output  [11:0] sbu2mlx_TUSER;
input   ap_clk;
input   ap_rst_n;
input   prt_nw2sbu_TVALID;
output   prt_nw2sbu_TREADY;
input   prt_cx2sbu_TVALID;
output   prt_cx2sbu_TREADY;
input   mlx2sbu_TVALID;
output   mlx2sbu_TREADY;
output   sbu2mlx_TVALID;
input   sbu2mlx_TREADY;
output   sbu2prt_nw_TVALID;
input   sbu2prt_nw_TREADY;
output   sbu2prt_cx_TVALID;
input   sbu2prt_cx_TREADY;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

reg ap_idle;

reg    ap_rst_n_inv;
wire    example_Block_codeRepl951_proc_U0_ap_start;
wire    example_Block_codeRepl951_proc_U0_ap_done;
wire    example_Block_codeRepl951_proc_U0_ap_continue;
wire    example_Block_codeRepl951_proc_U0_ap_idle;
wire    example_Block_codeRepl951_proc_U0_ap_ready;
wire    example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY;
wire    example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY;
wire    example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY;
wire   [255:0] example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA;
wire    example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID;
wire   [31:0] example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP;
wire   [0:0] example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST;
wire   [2:0] example_Block_codeRepl951_proc_U0_sbu2mlx_TID;
wire   [11:0] example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER;
wire   [255:0] example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA;
wire    example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID;
wire   [31:0] example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP;
wire   [0:0] example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST;
wire   [2:0] example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID;
wire   [11:0] example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER;
wire   [255:0] example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA;
wire    example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID;
wire   [31:0] example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP;
wire   [0:0] example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST;
wire   [2:0] example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID;
wire   [11:0] example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER;
wire    ap_sig_hs_continue;
reg    ap_sig_hs_done;
wire    ap_sig_hs_ready;

example_Block_codeRepl951_proc example_Block_codeRepl951_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(example_Block_codeRepl951_proc_U0_ap_start),
    .ap_done(example_Block_codeRepl951_proc_U0_ap_done),
    .ap_continue(example_Block_codeRepl951_proc_U0_ap_continue),
    .ap_idle(example_Block_codeRepl951_proc_U0_ap_idle),
    .ap_ready(example_Block_codeRepl951_proc_U0_ap_ready),
    .prt_nw2sbu_TDATA(prt_nw2sbu_TDATA),
    .prt_nw2sbu_TVALID(prt_nw2sbu_TVALID),
    .prt_nw2sbu_TREADY(example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY),
    .prt_nw2sbu_TKEEP(prt_nw2sbu_TKEEP),
    .prt_nw2sbu_TLAST(prt_nw2sbu_TLAST),
    .prt_nw2sbu_TID(prt_nw2sbu_TID),
    .prt_nw2sbu_TUSER(prt_nw2sbu_TUSER),
    .prt_cx2sbu_TDATA(prt_cx2sbu_TDATA),
    .prt_cx2sbu_TVALID(prt_cx2sbu_TVALID),
    .prt_cx2sbu_TREADY(example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY),
    .prt_cx2sbu_TKEEP(prt_cx2sbu_TKEEP),
    .prt_cx2sbu_TLAST(prt_cx2sbu_TLAST),
    .prt_cx2sbu_TID(prt_cx2sbu_TID),
    .prt_cx2sbu_TUSER(prt_cx2sbu_TUSER),
    .mlx2sbu_TDATA(mlx2sbu_TDATA),
    .mlx2sbu_TVALID(mlx2sbu_TVALID),
    .mlx2sbu_TREADY(example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY),
    .mlx2sbu_TKEEP(mlx2sbu_TKEEP),
    .mlx2sbu_TLAST(mlx2sbu_TLAST),
    .mlx2sbu_TID(mlx2sbu_TID),
    .mlx2sbu_TUSER(mlx2sbu_TUSER),
    .sbu2mlx_TDATA(example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA),
    .sbu2mlx_TVALID(example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID),
    .sbu2mlx_TREADY(sbu2mlx_TREADY),
    .sbu2mlx_TKEEP(example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP),
    .sbu2mlx_TLAST(example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST),
    .sbu2mlx_TID(example_Block_codeRepl951_proc_U0_sbu2mlx_TID),
    .sbu2mlx_TUSER(example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER),
    .sbu2prt_nw_TDATA(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA),
    .sbu2prt_nw_TVALID(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID),
    .sbu2prt_nw_TREADY(sbu2prt_nw_TREADY),
    .sbu2prt_nw_TKEEP(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP),
    .sbu2prt_nw_TLAST(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST),
    .sbu2prt_nw_TID(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID),
    .sbu2prt_nw_TUSER(example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER),
    .sbu2prt_cx_TDATA(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA),
    .sbu2prt_cx_TVALID(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID),
    .sbu2prt_cx_TREADY(sbu2prt_cx_TREADY),
    .sbu2prt_cx_TKEEP(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP),
    .sbu2prt_cx_TLAST(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST),
    .sbu2prt_cx_TID(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID),
    .sbu2prt_cx_TUSER(example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER)
);

always @ (*) begin
    if ((example_Block_codeRepl951_proc_U0_ap_idle == 1'b1)) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((example_Block_codeRepl951_proc_U0_ap_done == 1'b1)) begin
        ap_sig_hs_done = 1'b1;
    end else begin
        ap_sig_hs_done = 1'b0;
    end
end

assign ap_done = ap_sig_hs_done;

assign ap_ready = example_Block_codeRepl951_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = 1'b1;

assign ap_sig_hs_ready = example_Block_codeRepl951_proc_U0_ap_ready;

assign example_Block_codeRepl951_proc_U0_ap_continue = 1'b1;

assign example_Block_codeRepl951_proc_U0_ap_start = ap_start;

assign mlx2sbu_TREADY = example_Block_codeRepl951_proc_U0_mlx2sbu_TREADY;

assign prt_cx2sbu_TREADY = example_Block_codeRepl951_proc_U0_prt_cx2sbu_TREADY;

assign prt_nw2sbu_TREADY = example_Block_codeRepl951_proc_U0_prt_nw2sbu_TREADY;

assign sbu2mlx_TDATA = example_Block_codeRepl951_proc_U0_sbu2mlx_TDATA;

assign sbu2mlx_TID = example_Block_codeRepl951_proc_U0_sbu2mlx_TID;

assign sbu2mlx_TKEEP = example_Block_codeRepl951_proc_U0_sbu2mlx_TKEEP;

assign sbu2mlx_TLAST = example_Block_codeRepl951_proc_U0_sbu2mlx_TLAST;

assign sbu2mlx_TUSER = example_Block_codeRepl951_proc_U0_sbu2mlx_TUSER;

assign sbu2mlx_TVALID = example_Block_codeRepl951_proc_U0_sbu2mlx_TVALID;

assign sbu2prt_cx_TDATA = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TDATA;

assign sbu2prt_cx_TID = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TID;

assign sbu2prt_cx_TKEEP = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TKEEP;

assign sbu2prt_cx_TLAST = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TLAST;

assign sbu2prt_cx_TUSER = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TUSER;

assign sbu2prt_cx_TVALID = example_Block_codeRepl951_proc_U0_sbu2prt_cx_TVALID;

assign sbu2prt_nw_TDATA = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TDATA;

assign sbu2prt_nw_TID = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TID;

assign sbu2prt_nw_TKEEP = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TKEEP;

assign sbu2prt_nw_TLAST = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TLAST;

assign sbu2prt_nw_TUSER = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TUSER;

assign sbu2prt_nw_TVALID = example_Block_codeRepl951_proc_U0_sbu2prt_nw_TVALID;

endmodule //example
