// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "axi_stream_pass_alt.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic axi_stream_pass_alt::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic axi_stream_pass_alt::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> axi_stream_pass_alt::ap_ST_fsm_state1 = "1";
const sc_lv<2> axi_stream_pass_alt::ap_ST_fsm_state2 = "10";
const bool axi_stream_pass_alt::ap_const_boolean_1 = true;
const sc_lv<32> axi_stream_pass_alt::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> axi_stream_pass_alt::ap_const_lv1_1 = "1";
const sc_lv<1> axi_stream_pass_alt::ap_const_lv1_0 = "0";
const sc_lv<2> axi_stream_pass_alt::ap_const_lv2_0 = "00";
const sc_lv<2> axi_stream_pass_alt::ap_const_lv2_2 = "10";
const sc_lv<2> axi_stream_pass_alt::ap_const_lv2_3 = "11";
const sc_lv<2> axi_stream_pass_alt::ap_const_lv2_1 = "1";
const sc_lv<32> axi_stream_pass_alt::ap_const_lv32_1 = "1";

axi_stream_pass_alt::axi_stream_pass_alt(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Out_V_data_V_1_ack_in);
    sensitive << ( Out_V_data_V_1_state );

    SC_METHOD(thread_Out_V_data_V_1_ack_out);
    sensitive << ( sbu2mlx_TREADY );

    SC_METHOD(thread_Out_V_data_V_1_data_out);
    sensitive << ( Out_V_data_V_1_payload_A );
    sensitive << ( Out_V_data_V_1_payload_B );
    sensitive << ( Out_V_data_V_1_sel );

    SC_METHOD(thread_Out_V_data_V_1_load_A);
    sensitive << ( Out_V_data_V_1_sel_wr );
    sensitive << ( Out_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_data_V_1_load_B);
    sensitive << ( Out_V_data_V_1_sel_wr );
    sensitive << ( Out_V_data_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_data_V_1_sel);
    sensitive << ( Out_V_data_V_1_sel_rd );

    SC_METHOD(thread_Out_V_data_V_1_state_cmp_full);
    sensitive << ( Out_V_data_V_1_state );

    SC_METHOD(thread_Out_V_data_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_condition_346 );

    SC_METHOD(thread_Out_V_data_V_1_vld_out);
    sensitive << ( Out_V_data_V_1_state );

    SC_METHOD(thread_Out_V_id_V_1_ack_in);
    sensitive << ( Out_V_id_V_1_state );

    SC_METHOD(thread_Out_V_id_V_1_ack_out);
    sensitive << ( sbu2mlx_TREADY );

    SC_METHOD(thread_Out_V_id_V_1_data_out);
    sensitive << ( Out_V_id_V_1_payload_A );
    sensitive << ( Out_V_id_V_1_payload_B );
    sensitive << ( Out_V_id_V_1_sel );

    SC_METHOD(thread_Out_V_id_V_1_load_A);
    sensitive << ( Out_V_id_V_1_sel_wr );
    sensitive << ( Out_V_id_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_id_V_1_load_B);
    sensitive << ( Out_V_id_V_1_sel_wr );
    sensitive << ( Out_V_id_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_id_V_1_sel);
    sensitive << ( Out_V_id_V_1_sel_rd );

    SC_METHOD(thread_Out_V_id_V_1_state_cmp_full);
    sensitive << ( Out_V_id_V_1_state );

    SC_METHOD(thread_Out_V_id_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_condition_346 );

    SC_METHOD(thread_Out_V_id_V_1_vld_out);
    sensitive << ( Out_V_id_V_1_state );

    SC_METHOD(thread_Out_V_keep_V_1_ack_in);
    sensitive << ( Out_V_keep_V_1_state );

    SC_METHOD(thread_Out_V_keep_V_1_ack_out);
    sensitive << ( sbu2mlx_TREADY );

    SC_METHOD(thread_Out_V_keep_V_1_data_out);
    sensitive << ( Out_V_keep_V_1_payload_A );
    sensitive << ( Out_V_keep_V_1_payload_B );
    sensitive << ( Out_V_keep_V_1_sel );

    SC_METHOD(thread_Out_V_keep_V_1_load_A);
    sensitive << ( Out_V_keep_V_1_sel_wr );
    sensitive << ( Out_V_keep_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_keep_V_1_load_B);
    sensitive << ( Out_V_keep_V_1_sel_wr );
    sensitive << ( Out_V_keep_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_keep_V_1_sel);
    sensitive << ( Out_V_keep_V_1_sel_rd );

    SC_METHOD(thread_Out_V_keep_V_1_state_cmp_full);
    sensitive << ( Out_V_keep_V_1_state );

    SC_METHOD(thread_Out_V_keep_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_condition_346 );

    SC_METHOD(thread_Out_V_keep_V_1_vld_out);
    sensitive << ( Out_V_keep_V_1_state );

    SC_METHOD(thread_Out_V_last_V_1_ack_in);
    sensitive << ( Out_V_last_V_1_state );

    SC_METHOD(thread_Out_V_last_V_1_ack_out);
    sensitive << ( sbu2mlx_TREADY );

    SC_METHOD(thread_Out_V_last_V_1_data_out);
    sensitive << ( Out_V_last_V_1_payload_A );
    sensitive << ( Out_V_last_V_1_payload_B );
    sensitive << ( Out_V_last_V_1_sel );

    SC_METHOD(thread_Out_V_last_V_1_load_A);
    sensitive << ( Out_V_last_V_1_sel_wr );
    sensitive << ( Out_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_last_V_1_load_B);
    sensitive << ( Out_V_last_V_1_sel_wr );
    sensitive << ( Out_V_last_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_last_V_1_sel);
    sensitive << ( Out_V_last_V_1_sel_rd );

    SC_METHOD(thread_Out_V_last_V_1_state_cmp_full);
    sensitive << ( Out_V_last_V_1_state );

    SC_METHOD(thread_Out_V_last_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_condition_346 );

    SC_METHOD(thread_Out_V_last_V_1_vld_out);
    sensitive << ( Out_V_last_V_1_state );

    SC_METHOD(thread_Out_V_user_V_1_ack_in);
    sensitive << ( Out_V_user_V_1_state );

    SC_METHOD(thread_Out_V_user_V_1_ack_out);
    sensitive << ( sbu2mlx_TREADY );

    SC_METHOD(thread_Out_V_user_V_1_data_out);
    sensitive << ( Out_V_user_V_1_payload_A );
    sensitive << ( Out_V_user_V_1_payload_B );
    sensitive << ( Out_V_user_V_1_sel );

    SC_METHOD(thread_Out_V_user_V_1_load_A);
    sensitive << ( Out_V_user_V_1_sel_wr );
    sensitive << ( Out_V_user_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_user_V_1_load_B);
    sensitive << ( Out_V_user_V_1_sel_wr );
    sensitive << ( Out_V_user_V_1_state_cmp_full );

    SC_METHOD(thread_Out_V_user_V_1_sel);
    sensitive << ( Out_V_user_V_1_sel_rd );

    SC_METHOD(thread_Out_V_user_V_1_state_cmp_full);
    sensitive << ( Out_V_user_V_1_state );

    SC_METHOD(thread_Out_V_user_V_1_vld_in);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_condition_346 );

    SC_METHOD(thread_Out_V_user_V_1_vld_out);
    sensitive << ( Out_V_user_V_1_state );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_346);
    sensitive << ( ap_start );
    sensitive << ( mlx2sbu_TVALID );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );

    SC_METHOD(thread_ap_condition_391);
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( Out_V_keep_V_1_ack_in );
    sensitive << ( Out_V_last_V_1_ack_in );
    sensitive << ( Out_V_id_V_1_ack_in );
    sensitive << ( Out_V_user_V_1_ack_in );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_112 );
    sensitive << ( ap_condition_391 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_112 );
    sensitive << ( ap_condition_391 );

    SC_METHOD(thread_mlx2sbu_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mlx2sbu_TVALID );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );

    SC_METHOD(thread_mlx2sbu_TREADY);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_condition_346 );

    SC_METHOD(thread_sbu2mlx_TDATA);
    sensitive << ( Out_V_data_V_1_data_out );

    SC_METHOD(thread_sbu2mlx_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( Out_V_data_V_1_state );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_112 );

    SC_METHOD(thread_sbu2mlx_TID);
    sensitive << ( Out_V_id_V_1_data_out );

    SC_METHOD(thread_sbu2mlx_TKEEP);
    sensitive << ( Out_V_keep_V_1_data_out );

    SC_METHOD(thread_sbu2mlx_TLAST);
    sensitive << ( Out_V_last_V_1_data_out );

    SC_METHOD(thread_sbu2mlx_TUSER);
    sensitive << ( Out_V_user_V_1_data_out );

    SC_METHOD(thread_sbu2mlx_TVALID);
    sensitive << ( Out_V_user_V_1_state );

    SC_METHOD(thread_tmp_nbreadreq_fu_38_p7);
    sensitive << ( mlx2sbu_TVALID );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( Out_V_data_V_1_ack_in );
    sensitive << ( tmp_nbreadreq_fu_38_p7 );
    sensitive << ( tmp_reg_112 );
    sensitive << ( ap_condition_346 );
    sensitive << ( ap_condition_391 );

    ap_CS_fsm = "01";
    Out_V_data_V_1_sel_rd = SC_LOGIC_0;
    Out_V_data_V_1_sel_wr = SC_LOGIC_0;
    Out_V_data_V_1_state = "00";
    Out_V_keep_V_1_sel_rd = SC_LOGIC_0;
    Out_V_keep_V_1_sel_wr = SC_LOGIC_0;
    Out_V_keep_V_1_state = "00";
    Out_V_last_V_1_sel_rd = SC_LOGIC_0;
    Out_V_last_V_1_sel_wr = SC_LOGIC_0;
    Out_V_last_V_1_state = "00";
    Out_V_id_V_1_sel_rd = SC_LOGIC_0;
    Out_V_id_V_1_sel_wr = SC_LOGIC_0;
    Out_V_id_V_1_state = "00";
    Out_V_user_V_1_sel_rd = SC_LOGIC_0;
    Out_V_user_V_1_sel_wr = SC_LOGIC_0;
    Out_V_user_V_1_state = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "axi_stream_pass_alt_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, mlx2sbu_TDATA, "(port)mlx2sbu_TDATA");
    sc_trace(mVcdFile, mlx2sbu_TVALID, "(port)mlx2sbu_TVALID");
    sc_trace(mVcdFile, mlx2sbu_TREADY, "(port)mlx2sbu_TREADY");
    sc_trace(mVcdFile, mlx2sbu_TKEEP, "(port)mlx2sbu_TKEEP");
    sc_trace(mVcdFile, mlx2sbu_TLAST, "(port)mlx2sbu_TLAST");
    sc_trace(mVcdFile, mlx2sbu_TID, "(port)mlx2sbu_TID");
    sc_trace(mVcdFile, mlx2sbu_TUSER, "(port)mlx2sbu_TUSER");
    sc_trace(mVcdFile, sbu2mlx_TDATA, "(port)sbu2mlx_TDATA");
    sc_trace(mVcdFile, sbu2mlx_TVALID, "(port)sbu2mlx_TVALID");
    sc_trace(mVcdFile, sbu2mlx_TREADY, "(port)sbu2mlx_TREADY");
    sc_trace(mVcdFile, sbu2mlx_TKEEP, "(port)sbu2mlx_TKEEP");
    sc_trace(mVcdFile, sbu2mlx_TLAST, "(port)sbu2mlx_TLAST");
    sc_trace(mVcdFile, sbu2mlx_TID, "(port)sbu2mlx_TID");
    sc_trace(mVcdFile, sbu2mlx_TUSER, "(port)sbu2mlx_TUSER");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, Out_V_data_V_1_data_out, "Out_V_data_V_1_data_out");
    sc_trace(mVcdFile, Out_V_data_V_1_vld_in, "Out_V_data_V_1_vld_in");
    sc_trace(mVcdFile, Out_V_data_V_1_vld_out, "Out_V_data_V_1_vld_out");
    sc_trace(mVcdFile, Out_V_data_V_1_ack_in, "Out_V_data_V_1_ack_in");
    sc_trace(mVcdFile, Out_V_data_V_1_ack_out, "Out_V_data_V_1_ack_out");
    sc_trace(mVcdFile, Out_V_data_V_1_payload_A, "Out_V_data_V_1_payload_A");
    sc_trace(mVcdFile, Out_V_data_V_1_payload_B, "Out_V_data_V_1_payload_B");
    sc_trace(mVcdFile, Out_V_data_V_1_sel_rd, "Out_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, Out_V_data_V_1_sel_wr, "Out_V_data_V_1_sel_wr");
    sc_trace(mVcdFile, Out_V_data_V_1_sel, "Out_V_data_V_1_sel");
    sc_trace(mVcdFile, Out_V_data_V_1_load_A, "Out_V_data_V_1_load_A");
    sc_trace(mVcdFile, Out_V_data_V_1_load_B, "Out_V_data_V_1_load_B");
    sc_trace(mVcdFile, Out_V_data_V_1_state, "Out_V_data_V_1_state");
    sc_trace(mVcdFile, Out_V_data_V_1_state_cmp_full, "Out_V_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, Out_V_keep_V_1_data_out, "Out_V_keep_V_1_data_out");
    sc_trace(mVcdFile, Out_V_keep_V_1_vld_in, "Out_V_keep_V_1_vld_in");
    sc_trace(mVcdFile, Out_V_keep_V_1_vld_out, "Out_V_keep_V_1_vld_out");
    sc_trace(mVcdFile, Out_V_keep_V_1_ack_in, "Out_V_keep_V_1_ack_in");
    sc_trace(mVcdFile, Out_V_keep_V_1_ack_out, "Out_V_keep_V_1_ack_out");
    sc_trace(mVcdFile, Out_V_keep_V_1_payload_A, "Out_V_keep_V_1_payload_A");
    sc_trace(mVcdFile, Out_V_keep_V_1_payload_B, "Out_V_keep_V_1_payload_B");
    sc_trace(mVcdFile, Out_V_keep_V_1_sel_rd, "Out_V_keep_V_1_sel_rd");
    sc_trace(mVcdFile, Out_V_keep_V_1_sel_wr, "Out_V_keep_V_1_sel_wr");
    sc_trace(mVcdFile, Out_V_keep_V_1_sel, "Out_V_keep_V_1_sel");
    sc_trace(mVcdFile, Out_V_keep_V_1_load_A, "Out_V_keep_V_1_load_A");
    sc_trace(mVcdFile, Out_V_keep_V_1_load_B, "Out_V_keep_V_1_load_B");
    sc_trace(mVcdFile, Out_V_keep_V_1_state, "Out_V_keep_V_1_state");
    sc_trace(mVcdFile, Out_V_keep_V_1_state_cmp_full, "Out_V_keep_V_1_state_cmp_full");
    sc_trace(mVcdFile, Out_V_last_V_1_data_out, "Out_V_last_V_1_data_out");
    sc_trace(mVcdFile, Out_V_last_V_1_vld_in, "Out_V_last_V_1_vld_in");
    sc_trace(mVcdFile, Out_V_last_V_1_vld_out, "Out_V_last_V_1_vld_out");
    sc_trace(mVcdFile, Out_V_last_V_1_ack_in, "Out_V_last_V_1_ack_in");
    sc_trace(mVcdFile, Out_V_last_V_1_ack_out, "Out_V_last_V_1_ack_out");
    sc_trace(mVcdFile, Out_V_last_V_1_payload_A, "Out_V_last_V_1_payload_A");
    sc_trace(mVcdFile, Out_V_last_V_1_payload_B, "Out_V_last_V_1_payload_B");
    sc_trace(mVcdFile, Out_V_last_V_1_sel_rd, "Out_V_last_V_1_sel_rd");
    sc_trace(mVcdFile, Out_V_last_V_1_sel_wr, "Out_V_last_V_1_sel_wr");
    sc_trace(mVcdFile, Out_V_last_V_1_sel, "Out_V_last_V_1_sel");
    sc_trace(mVcdFile, Out_V_last_V_1_load_A, "Out_V_last_V_1_load_A");
    sc_trace(mVcdFile, Out_V_last_V_1_load_B, "Out_V_last_V_1_load_B");
    sc_trace(mVcdFile, Out_V_last_V_1_state, "Out_V_last_V_1_state");
    sc_trace(mVcdFile, Out_V_last_V_1_state_cmp_full, "Out_V_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, Out_V_id_V_1_data_out, "Out_V_id_V_1_data_out");
    sc_trace(mVcdFile, Out_V_id_V_1_vld_in, "Out_V_id_V_1_vld_in");
    sc_trace(mVcdFile, Out_V_id_V_1_vld_out, "Out_V_id_V_1_vld_out");
    sc_trace(mVcdFile, Out_V_id_V_1_ack_in, "Out_V_id_V_1_ack_in");
    sc_trace(mVcdFile, Out_V_id_V_1_ack_out, "Out_V_id_V_1_ack_out");
    sc_trace(mVcdFile, Out_V_id_V_1_payload_A, "Out_V_id_V_1_payload_A");
    sc_trace(mVcdFile, Out_V_id_V_1_payload_B, "Out_V_id_V_1_payload_B");
    sc_trace(mVcdFile, Out_V_id_V_1_sel_rd, "Out_V_id_V_1_sel_rd");
    sc_trace(mVcdFile, Out_V_id_V_1_sel_wr, "Out_V_id_V_1_sel_wr");
    sc_trace(mVcdFile, Out_V_id_V_1_sel, "Out_V_id_V_1_sel");
    sc_trace(mVcdFile, Out_V_id_V_1_load_A, "Out_V_id_V_1_load_A");
    sc_trace(mVcdFile, Out_V_id_V_1_load_B, "Out_V_id_V_1_load_B");
    sc_trace(mVcdFile, Out_V_id_V_1_state, "Out_V_id_V_1_state");
    sc_trace(mVcdFile, Out_V_id_V_1_state_cmp_full, "Out_V_id_V_1_state_cmp_full");
    sc_trace(mVcdFile, Out_V_user_V_1_data_out, "Out_V_user_V_1_data_out");
    sc_trace(mVcdFile, Out_V_user_V_1_vld_in, "Out_V_user_V_1_vld_in");
    sc_trace(mVcdFile, Out_V_user_V_1_vld_out, "Out_V_user_V_1_vld_out");
    sc_trace(mVcdFile, Out_V_user_V_1_ack_in, "Out_V_user_V_1_ack_in");
    sc_trace(mVcdFile, Out_V_user_V_1_ack_out, "Out_V_user_V_1_ack_out");
    sc_trace(mVcdFile, Out_V_user_V_1_payload_A, "Out_V_user_V_1_payload_A");
    sc_trace(mVcdFile, Out_V_user_V_1_payload_B, "Out_V_user_V_1_payload_B");
    sc_trace(mVcdFile, Out_V_user_V_1_sel_rd, "Out_V_user_V_1_sel_rd");
    sc_trace(mVcdFile, Out_V_user_V_1_sel_wr, "Out_V_user_V_1_sel_wr");
    sc_trace(mVcdFile, Out_V_user_V_1_sel, "Out_V_user_V_1_sel");
    sc_trace(mVcdFile, Out_V_user_V_1_load_A, "Out_V_user_V_1_load_A");
    sc_trace(mVcdFile, Out_V_user_V_1_load_B, "Out_V_user_V_1_load_B");
    sc_trace(mVcdFile, Out_V_user_V_1_state, "Out_V_user_V_1_state");
    sc_trace(mVcdFile, Out_V_user_V_1_state_cmp_full, "Out_V_user_V_1_state_cmp_full");
    sc_trace(mVcdFile, mlx2sbu_TDATA_blk_n, "mlx2sbu_TDATA_blk_n");
    sc_trace(mVcdFile, tmp_nbreadreq_fu_38_p7, "tmp_nbreadreq_fu_38_p7");
    sc_trace(mVcdFile, sbu2mlx_TDATA_blk_n, "sbu2mlx_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_reg_112, "tmp_reg_112");
    sc_trace(mVcdFile, ap_condition_346, "ap_condition_346");
    sc_trace(mVcdFile, ap_condition_391, "ap_condition_391");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

axi_stream_pass_alt::~axi_stream_pass_alt() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void axi_stream_pass_alt::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_vld_out.read()))) {
            Out_V_data_V_1_sel_rd =  (sc_logic) (~Out_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_ack_in.read()))) {
            Out_V_data_V_1_sel_wr =  (sc_logic) (~Out_V_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            Out_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            Out_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(Out_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_ack_out.read()))))) {
            Out_V_data_V_1_state = ap_const_lv2_3;
        } else {
            Out_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_id_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_vld_out.read()))) {
            Out_V_id_V_1_sel_rd =  (sc_logic) (~Out_V_id_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_id_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_ack_in.read()))) {
            Out_V_id_V_1_sel_wr =  (sc_logic) (~Out_V_id_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_id_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, Out_V_id_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_id_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_id_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_id_V_1_state.read())))) {
            Out_V_id_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, Out_V_id_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_id_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_id_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_id_V_1_state.read())))) {
            Out_V_id_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_id_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_id_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_id_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, Out_V_id_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, Out_V_id_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_ack_out.read()))))) {
            Out_V_id_V_1_state = ap_const_lv2_3;
        } else {
            Out_V_id_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_keep_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_vld_out.read()))) {
            Out_V_keep_V_1_sel_rd =  (sc_logic) (~Out_V_keep_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_keep_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_ack_in.read()))) {
            Out_V_keep_V_1_sel_wr =  (sc_logic) (~Out_V_keep_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_keep_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, Out_V_keep_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_keep_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_keep_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_keep_V_1_state.read())))) {
            Out_V_keep_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, Out_V_keep_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_keep_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_keep_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_keep_V_1_state.read())))) {
            Out_V_keep_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_keep_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_keep_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_keep_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, Out_V_keep_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, Out_V_keep_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_ack_out.read()))))) {
            Out_V_keep_V_1_state = ap_const_lv2_3;
        } else {
            Out_V_keep_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_vld_out.read()))) {
            Out_V_last_V_1_sel_rd =  (sc_logic) (~Out_V_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_ack_in.read()))) {
            Out_V_last_V_1_sel_wr =  (sc_logic) (~Out_V_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, Out_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_last_V_1_state.read())))) {
            Out_V_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, Out_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_last_V_1_state.read())))) {
            Out_V_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, Out_V_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, Out_V_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_ack_out.read()))))) {
            Out_V_last_V_1_state = ap_const_lv2_3;
        } else {
            Out_V_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_user_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_vld_out.read()))) {
            Out_V_user_V_1_sel_rd =  (sc_logic) (~Out_V_user_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_user_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_ack_in.read()))) {
            Out_V_user_V_1_sel_wr =  (sc_logic) (~Out_V_user_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        Out_V_user_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, Out_V_user_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_user_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_user_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_user_V_1_state.read())))) {
            Out_V_user_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, Out_V_user_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_user_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, Out_V_user_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_user_V_1_state.read())))) {
            Out_V_user_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, Out_V_user_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, Out_V_user_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, Out_V_user_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, Out_V_user_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, Out_V_user_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_ack_out.read()))))) {
            Out_V_user_V_1_state = ap_const_lv2_3;
        } else {
            Out_V_user_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_load_A.read())) {
        Out_V_data_V_1_payload_A = mlx2sbu_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_load_B.read())) {
        Out_V_data_V_1_payload_B = mlx2sbu_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_load_A.read())) {
        Out_V_id_V_1_payload_A = mlx2sbu_TID.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_load_B.read())) {
        Out_V_id_V_1_payload_B = mlx2sbu_TID.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_load_A.read())) {
        Out_V_keep_V_1_payload_A = mlx2sbu_TKEEP.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_load_B.read())) {
        Out_V_keep_V_1_payload_B = mlx2sbu_TKEEP.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_load_A.read())) {
        Out_V_last_V_1_payload_A = mlx2sbu_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_load_B.read())) {
        Out_V_last_V_1_payload_B = mlx2sbu_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_load_A.read())) {
        Out_V_user_V_1_payload_A = mlx2sbu_TUSER.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_load_B.read())) {
        Out_V_user_V_1_payload_B = mlx2sbu_TUSER.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        tmp_reg_112 = tmp_nbreadreq_fu_38_p7.read();
    }
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_ack_in() {
    Out_V_data_V_1_ack_in =  (sc_logic) (Out_V_data_V_1_state.read()[1]);
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_ack_out() {
    Out_V_data_V_1_ack_out = sbu2mlx_TREADY.read();
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_data_V_1_sel.read())) {
        Out_V_data_V_1_data_out = Out_V_data_V_1_payload_B.read();
    } else {
        Out_V_data_V_1_data_out = Out_V_data_V_1_payload_A.read();
    }
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_load_A() {
    Out_V_data_V_1_load_A = (Out_V_data_V_1_state_cmp_full.read() & ~Out_V_data_V_1_sel_wr.read());
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_load_B() {
    Out_V_data_V_1_load_B = (Out_V_data_V_1_sel_wr.read() & Out_V_data_V_1_state_cmp_full.read());
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_sel() {
    Out_V_data_V_1_sel = Out_V_data_V_1_sel_rd.read();
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_state_cmp_full() {
    Out_V_data_V_1_state_cmp_full =  (sc_logic) ((!Out_V_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(Out_V_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
         !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        Out_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        Out_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_Out_V_data_V_1_vld_out() {
    Out_V_data_V_1_vld_out =  (sc_logic) (Out_V_data_V_1_state.read()[0]);
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_ack_in() {
    Out_V_id_V_1_ack_in =  (sc_logic) (Out_V_id_V_1_state.read()[1]);
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_ack_out() {
    Out_V_id_V_1_ack_out = sbu2mlx_TREADY.read();
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_id_V_1_sel.read())) {
        Out_V_id_V_1_data_out = Out_V_id_V_1_payload_B.read();
    } else {
        Out_V_id_V_1_data_out = Out_V_id_V_1_payload_A.read();
    }
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_load_A() {
    Out_V_id_V_1_load_A = (Out_V_id_V_1_state_cmp_full.read() & ~Out_V_id_V_1_sel_wr.read());
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_load_B() {
    Out_V_id_V_1_load_B = (Out_V_id_V_1_sel_wr.read() & Out_V_id_V_1_state_cmp_full.read());
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_sel() {
    Out_V_id_V_1_sel = Out_V_id_V_1_sel_rd.read();
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_state_cmp_full() {
    Out_V_id_V_1_state_cmp_full =  (sc_logic) ((!Out_V_id_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(Out_V_id_V_1_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
         !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        Out_V_id_V_1_vld_in = ap_const_logic_1;
    } else {
        Out_V_id_V_1_vld_in = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_Out_V_id_V_1_vld_out() {
    Out_V_id_V_1_vld_out =  (sc_logic) (Out_V_id_V_1_state.read()[0]);
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_ack_in() {
    Out_V_keep_V_1_ack_in =  (sc_logic) (Out_V_keep_V_1_state.read()[1]);
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_ack_out() {
    Out_V_keep_V_1_ack_out = sbu2mlx_TREADY.read();
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_keep_V_1_sel.read())) {
        Out_V_keep_V_1_data_out = Out_V_keep_V_1_payload_B.read();
    } else {
        Out_V_keep_V_1_data_out = Out_V_keep_V_1_payload_A.read();
    }
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_load_A() {
    Out_V_keep_V_1_load_A = (Out_V_keep_V_1_state_cmp_full.read() & ~Out_V_keep_V_1_sel_wr.read());
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_load_B() {
    Out_V_keep_V_1_load_B = (Out_V_keep_V_1_sel_wr.read() & Out_V_keep_V_1_state_cmp_full.read());
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_sel() {
    Out_V_keep_V_1_sel = Out_V_keep_V_1_sel_rd.read();
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_state_cmp_full() {
    Out_V_keep_V_1_state_cmp_full =  (sc_logic) ((!Out_V_keep_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(Out_V_keep_V_1_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
         !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        Out_V_keep_V_1_vld_in = ap_const_logic_1;
    } else {
        Out_V_keep_V_1_vld_in = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_Out_V_keep_V_1_vld_out() {
    Out_V_keep_V_1_vld_out =  (sc_logic) (Out_V_keep_V_1_state.read()[0]);
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_ack_in() {
    Out_V_last_V_1_ack_in =  (sc_logic) (Out_V_last_V_1_state.read()[1]);
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_ack_out() {
    Out_V_last_V_1_ack_out = sbu2mlx_TREADY.read();
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_last_V_1_sel.read())) {
        Out_V_last_V_1_data_out = Out_V_last_V_1_payload_B.read();
    } else {
        Out_V_last_V_1_data_out = Out_V_last_V_1_payload_A.read();
    }
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_load_A() {
    Out_V_last_V_1_load_A = (Out_V_last_V_1_state_cmp_full.read() & ~Out_V_last_V_1_sel_wr.read());
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_load_B() {
    Out_V_last_V_1_load_B = (Out_V_last_V_1_sel_wr.read() & Out_V_last_V_1_state_cmp_full.read());
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_sel() {
    Out_V_last_V_1_sel = Out_V_last_V_1_sel_rd.read();
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_state_cmp_full() {
    Out_V_last_V_1_state_cmp_full =  (sc_logic) ((!Out_V_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(Out_V_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
         !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        Out_V_last_V_1_vld_in = ap_const_logic_1;
    } else {
        Out_V_last_V_1_vld_in = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_Out_V_last_V_1_vld_out() {
    Out_V_last_V_1_vld_out =  (sc_logic) (Out_V_last_V_1_state.read()[0]);
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_ack_in() {
    Out_V_user_V_1_ack_in =  (sc_logic) (Out_V_user_V_1_state.read()[1]);
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_ack_out() {
    Out_V_user_V_1_ack_out = sbu2mlx_TREADY.read();
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, Out_V_user_V_1_sel.read())) {
        Out_V_user_V_1_data_out = Out_V_user_V_1_payload_B.read();
    } else {
        Out_V_user_V_1_data_out = Out_V_user_V_1_payload_A.read();
    }
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_load_A() {
    Out_V_user_V_1_load_A = (Out_V_user_V_1_state_cmp_full.read() & ~Out_V_user_V_1_sel_wr.read());
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_load_B() {
    Out_V_user_V_1_load_B = (Out_V_user_V_1_sel_wr.read() & Out_V_user_V_1_state_cmp_full.read());
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_sel() {
    Out_V_user_V_1_sel = Out_V_user_V_1_sel_rd.read();
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_state_cmp_full() {
    Out_V_user_V_1_state_cmp_full =  (sc_logic) ((!Out_V_user_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(Out_V_user_V_1_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
         !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        Out_V_user_V_1_vld_in = ap_const_logic_1;
    } else {
        Out_V_user_V_1_vld_in = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_Out_V_user_V_1_vld_out() {
    Out_V_user_V_1_vld_out =  (sc_logic) (Out_V_user_V_1_state.read()[0]);
}

void axi_stream_pass_alt::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void axi_stream_pass_alt::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void axi_stream_pass_alt::thread_ap_condition_346() {
    ap_condition_346 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(mlx2sbu_TVALID.read(), ap_const_logic_0)));
}

void axi_stream_pass_alt::thread_ap_condition_391() {
    ap_condition_391 = (esl_seteq<1,1,1>(Out_V_data_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(Out_V_keep_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(Out_V_last_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(Out_V_id_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(Out_V_user_V_1_ack_in.read(), ap_const_logic_0));
}

void axi_stream_pass_alt::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_condition_391.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_112.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read())))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_condition_391.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_112.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_mlx2sbu_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()))) {
        mlx2sbu_TDATA_blk_n = mlx2sbu_TVALID.read();
    } else {
        mlx2sbu_TDATA_blk_n = ap_const_logic_1;
    }
}

void axi_stream_pass_alt::thread_mlx2sbu_TREADY() {
    if (((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
          !(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read())))))) {
        mlx2sbu_TREADY = ap_const_logic_1;
    } else {
        mlx2sbu_TREADY = ap_const_logic_0;
    }
}

void axi_stream_pass_alt::thread_sbu2mlx_TDATA() {
    sbu2mlx_TDATA = Out_V_data_V_1_data_out.read();
}

void axi_stream_pass_alt::thread_sbu2mlx_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_112.read())))) {
        sbu2mlx_TDATA_blk_n =  (sc_logic) (Out_V_data_V_1_state.read()[1]);
    } else {
        sbu2mlx_TDATA_blk_n = ap_const_logic_1;
    }
}

void axi_stream_pass_alt::thread_sbu2mlx_TID() {
    sbu2mlx_TID = Out_V_id_V_1_data_out.read();
}

void axi_stream_pass_alt::thread_sbu2mlx_TKEEP() {
    sbu2mlx_TKEEP = Out_V_keep_V_1_data_out.read();
}

void axi_stream_pass_alt::thread_sbu2mlx_TLAST() {
    sbu2mlx_TLAST = Out_V_last_V_1_data_out.read();
}

void axi_stream_pass_alt::thread_sbu2mlx_TUSER() {
    sbu2mlx_TUSER = Out_V_user_V_1_data_out.read();
}

void axi_stream_pass_alt::thread_sbu2mlx_TVALID() {
    sbu2mlx_TVALID =  (sc_logic) (Out_V_user_V_1_state.read()[0]);
}

void axi_stream_pass_alt::thread_tmp_nbreadreq_fu_38_p7() {
    tmp_nbreadreq_fu_38_p7 =  (sc_lv<1>) ((mlx2sbu_TVALID.read()));
}

void axi_stream_pass_alt::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!(esl_seteq<1,1,1>(ap_condition_346.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_nbreadreq_fu_38_p7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_condition_391.read(), ap_const_boolean_1) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_112.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, Out_V_data_V_1_ack_in.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

